### ISSUE TITLE
converting adjacency matrix into numpy is slow

### ISSUE THREAD

**Issue by idc9** [igraph/python-igraph#111]
Converting the adjacency matrix into a numpy array using the following method is pretty slow. I tried a few other ways of doing this to no avail.

```
G.summary()
```
> IGRAPH DN-- 27885 234312 --

``` 
%%time
A = np.array(G.get_adjacency().data)
```
> CPU times: user 3min 23s, sys: 1min 18s, total: 4min 42s
> Wall time: 5min 31s

`.get_adjacency()` took about 3.5 min and `np.array(--)` took about 2 minutes.

Q: is there a faster way of getting the adjacency matrix as a numpy array?

Q: why is this method so slow (just curious)?

I'm using python 2.7,  OS X 10.11.6,  igraph 0.7.1, and numpy 1.11.1

**Comment by ntamas** [comment]
> why is this method so slow (just curious)?
`G.get_adjacency()` gives you a dense matrix, that's why it's slow. `np.array()` would also be a dense matrix for what it's worth, so it's gonna be slow either way. You need a sparse matrix instead.

> is there a faster way of getting the adjacency matrix as a numpy array?
If you really want a NumPy array and not a SciPy sparse matrix:

```
n = G.vcount()
a = np.zeros((n, n))
rows, cols = zip(*G.get_edgelist())
a[rows, cols] = 1
```

If you are on Python 3.x, you probably need to wrap the `zip()` call in `list()` first.
