### ISSUE TITLE
Not able to import python-igraph for Python 3.6

### ISSUE THREAD

**Issue by mohkar123** [igraph/python-igraph#125]
Hello,

I have the latest igraph version (0.7.1) and I am using Python 3.6 through ipython(Anaconda distribution). I first tried pip install,it successfully installs. But while importing, I am getting this error:
**ImportError: /home/user/anaconda3/lib/python3.6/site-packages/igraph/_igraph.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev**
I even have gmp installed
libgmp-dev:amd64				install
libgmp10:amd64					install
libgmp3-dev					install
libgmpxx4ldbl:amd64				install

Please help..

**Comment by ntamas** [comment]
Sorry, we do not support Anaconda Python. Most likely the package is compiled against the system-wide version of the standard C++ library but it is then linked to whatever version Anaconda is shipping with itself.

**Comment by mohkar123** [comment]
How should I run it? I also have Python 3.5 on which I was again getting the same error even though that was not linked with the Anaconda Distribution

**Comment by ntamas** [comment]
Sorry, I have no idea -- I have just tried installing `python-igraph` from source on a clean Ubuntu Linux virtual machine with Python 3.5 and it worked just fine. It also worked just fine within a Python 3.5 virtualenv. I am inclined to say that your issue is something that is specific to your particular machine only. If you think it is not, please send me step-by-step instructions about how to reproduce it on a clean, freshly installed machine.
