### ISSUE TITLE
Preventing text-to-path conversion

### ISSUE THREAD

**Issue by kfuku52** [igraph/python-igraph#136]
Hi, I would like to draw a svg file with preserved text information rather than converting them into paths. It might be a Cairo issue but is there any way to do so?

**Comment by ntamas** [comment]
There is a separate `write_svg()` method on the Graph class which does not use Cairo - it writes the SVG file directly. I'm pretty sure that this one will preserve the text as text (instead of converting it to paths), although its output won't look the same as the one that comes from Cairo and might not support all the graphics features that the Cairo-based plotting does. (I'm thinking about curved edges). Basic formatting like vertex and edge colors and sizes should be supported.

**Comment by kfuku52** [comment]
Thank you for your suggestion. `write_svg()` does not seem to fit my use because I need edge labels and other unsupported features. But it is good to know, I will try this method at another time when appropriate.
