### ISSUE TITLE
Provide documentation in release tarballs

### ISSUE THREAD

**Issue by hlef** [igraph/python-igraph#139]
Dear python-igraph developers,

Is there a special reason why documentation isn't provided in the official release tarball ?

This is quite unpractical for distributions [willing to build documentation packages](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780124).

Thanks for your work.

Regards,
 Hugo

**Comment by ntamas** [comment]
Sorry for the late reply, this has fallen through the cracks somehow.

Anyway, the API documentation (i.e. the one that you can find on https://pythonhosted.org/python-igraph/ ) is not in the source tarball because it can be generated from the source using Epydoc. There is a script in the released source tarball (`scripts/mkdoc.sh`) that generates the API documentation. Would that be enough to build a documentation package for igraph in Debian?

The "other" documentation in `doc/source` is not in the tarball because it's not finished yet. But considering the time that I can dedicate to the development of the Python interface (or, well, the lack thereof), I don't think that it will ever be finished. I see no point in including it in any sort of documentation package in its present form.

**Comment by hlef** [comment]
Hum, I didn't notice this script. Yes this would be enough.

Thanks !
