### ISSUE TITLE
NMI measure in compare_communities fails.

### ISSUE THREAD

**Issue by viraj96** [igraph/python-igraph#143]
Hi, Why is it necessary for the 2 communities to be of same length in `compare_communities` method. Does `nmi` have any such restriction. How else can we compare communities other than `modularity` metric?

**Comment by ntamas** [comment]
They have to be of the same size because that's how these metrics are defined in the literature. The two community structures being compared must be defined on the same graph so they must have the same number of nodes. This applies to all measures implemented by compare_communities.

Note that modularity is not meant to be used for comparison between graphs of different sizes either.

**Comment by viraj96** [comment]
Okay, so how can I delete nodes from a `vertex clustering` object so that I only remove nodes but remaining nodes remain in their original partition?

**Comment by ntamas** [comment]
Assign the membership vector to the vertices of the original graph as vertex attributes, then delete the vertices that you don't need, and create a new `VertexClustering`:

```
new_graph = graph.copy()
new_graph.vs["membership"] = graphPartition.membership
new_graph.delete_vertices(selection)
new_graphPartition = ig.VertexClustering(new_graph, new_graph.vs["membership"])
```

But please note that this is an issue tracker and not a support forum; it should be used for reporting bugs in the code of `python-igraph`. If you need help with using `python-igraph`, please send your questions to the igraph-help@nongnu.org mailing list after subscribing to it.
