### ISSUE TITLE
layout_grid_fruchterman_reingold

### ISSUE THREAD

**Issue by nicolaselie** [igraph/python-igraph#152]
Hello,

I have got the following error when trying to use `layout_grid_fruchterman_reingold`. `layout_fruchterman_reingold` works fine.

``` python
>>> import igraph as ig
>>> ig.__version__
'0.7.1+4.bed07760'
>>> g = ig.Graph()
>>> g.add_vertices(100)
>>> g.layout_fruchterman_reingold()
<Layout with 100 vertices and 2 dimensions>
>>> g.layout_grid_fruchterman_reingold()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\elie\AppData\Local\Continuum\Anaconda3\lib\site-packages\igraph\__init__.py", line 3949, in result
    layout = func(*args, **kwds)
  File "C:\Users\****\AppData\Local\Continuum\Anaconda3\lib\site-packages\igraph\__init__.py", line 1505, in layout_grid_fruchterman_reingold
    return self.layout_fruchterman_reingold(*args, **kwds)
  File "C:\Users\****\AppData\Local\Continuum\Anaconda3\lib\site-packages\igraph\__init__.py", line 3949, in result
    layout = func(*args, **kwds)
TypeError: 'grid' is an invalid keyword argument for this function
```

Any idea on what's going on?
My setup:
```
> python
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
I also tried on a GNU/Linux system, on I encountered the same error.

Thanks in advance,
Nicolas

**Comment by ntamas** [comment]
It works just fine on my machine, so I suspect that there's a version mismatch between the C core of the library (that's what you see as `0.7.1+4.bed07760`) and the Python interface. Basically, the story goes like this:

* `layout_fruchterman_reingold()` and `layout_grid_fruchterman_reingold()` used to be separate functions, but they were unified later

* To ease the transition, `layout_grid_fruchterman_reingold()` simply calls `layout_fruchterman_reingold(..., grid=True)` behind the scenes

[This is the commit](https://github.com/igraph/python-igraph/commit/180d7ca758d1bd511f7d68a3a515c7b8cb9e716d) where the `grid=...` parameter was introduced along with the redirection. Since this was an atomic change, I don't see how it could have happened that the redirection is in place but `layout_fruchterman_reingold()` does not "understand" the argument.

As a workaround, you can try `GraphBase.layout_grid_fruchterman_reingold(g)`, which tries to invoke the "old" grid-based algorithm directly.

**Comment by nicolaselie** [comment]
Thanks for your help!

I am unsure about the version of python-igraph's I have installed because I got it from an anaconda repository.

So, I tried your workaround but got the following error:
``` python
>>> ig.GraphBase.layout_grid_fruchterman_reingold(g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'igraph.Graph' has no attribute 'layout_grid_fruchterman_reingold'
```
I also tried again on my Linux PC (Arch based, python-igraph and igraph installed via pacman) and got the same problem than reported, either with Python 3.6 or Python 2.7.
Here it's igraph 0.7.1 and python-igraph 0.7.1.post6. It should be compatible, isn't it?

I wanted to compile it myself but failed on Windows. Maybe it will be easier on Linux.

**Comment by nicolaselie** [comment]
Ok, so I compiled trunk versions of C core and python-igraph and it works just fine.
The problem seems to be fixed so you can close the issue.

Thanks again for your help

**Comment by ntamas** [comment]
Thanks for following this up.

**Comment by tedmoore** [comment]
Greetings, 

Thanks for sorting this. Can someone direct me how to "compile the trunk version of C core and python-igraph"? I am getting the same error and would like to fix it!

Thank you!
Ted

> Ok, so I compiled trunk versions of C core and python-igraph and it works just fine.
> The problem seems to be fixed so you can close the issue.
> 
> Thanks again for your help

**Comment by vtraag** [comment]
Right now, the easiest way is to clone the repository using

```
git clone --recurse-submodules git://github.com/igraph/python-igraph.git
```

and then run

```
python setup.py install
```
