### ISSUE TITLE
PyPI version of igraph is very old

### ISSUE THREAD

**Issue by Calvin-L** [igraph/python-igraph#157]
Forgive me if this is a foolish question; I'm not sure of this project's status or release schedule.

The version of [igraph in PyPI](https://pypi.python.org/pypi/python-igraph/) was last updated in 2015, two and a half years ago. I am currently being bitten by igraph/igraph#858, which was fixed a short while after but does not seem to have made it in.

I am able to work around the problem, but it would be nice to have a newer igraph version in PyPI so I can save myself some lines of code.

**Comment by ntamas** [comment]
The problem is that unlike the R interface of igraph, the Python interface is dynamically linked to a corresponding version of the C core of igraph - so, the version on PyPI cannot be updated to use a newer C core until that newer version of the C core is formally released. The version on PyPI is 0.7.1post6, which downloads version 0.7.1 of the C core (the last official release) and then provides a Python interface to it, so that's why it is also two and a half years old (just like the corresponding C version).

Ideally, @gaborcsardi should release a new version of the C core from its present state, call it 1.0.0, and then I could release python-igraph 1.0.0 that depends on version 1.0.0 of the C core and it would include all the bug fixes and new features that have been added to the C core.

**Comment by gokceneraslan** [comment]
I think he's asking for a `python-igraph` update for python-only bugfixes to be included in PyPI package. I also need so many bug fixes such as: https://github.com/igraph/python-igraph/issues/88 and https://github.com/igraph/python-igraph/issues/115 that are not included in latest python-igraph package.

A new release would be really great!

**Comment by Calvin-L** [comment]
@gokceneraslan The particular bugfix that I need lives in the C core, so it is indeed as complicated as @ntamas suggested.

As I said, I can work around the problem so this isn't urgent---but I suppose take it as a vote from the community that a new release is wanted. 😄

**Comment by dashng** [comment]
@ntamas any schedule on release 1.0.0, i need some DH layout of the new version.

I try to install the development version from the source code. But it is really too difficult to install.

A alot of issues shown during the install.

Do you have some docs about installing development version on centos 7 and mac os?

**Comment by ntamas** [comment]
No scheduled date; sorry, I am very busy with other things in the next few weeks and I am not doing research any more so igraph is not on my list of priorities right now. Releasing a new version of the Python interface right now would either require me to go through the commit history of the Python interface since the release date of the last C core and figure out which changes are compatible with the old version of the C core and which ones are not (so it still compiles with a stock igraph 0.7.1), _or_ it would mean that I need to include a compatible version of the C core in the source code of the Python distribution directly (sort of an "unofficial" release of the C core beyond version 0.7.1). Both of these changes are larger (in scope) than the spare time I could dedicate to it. So, sorry, there won't be a new version of the Python interface in the next few weeks unless someone files a pull request. :(

> Do you have some docs about installing development version on centos 7 and mac os?

`pip install -U git+https://github.com/igraph/python-igraph.git --install-option="--c-core-url=https://github.com/igraph/igraph/archive/master.tar.gz"` should do the trick if you have all the required development tools on your machine. (E.g., a decent C compiler, `glibtoolize`, `libxml2-dev` and stuff). If you run into problems, provide some details (error message, compilation logs etc) and then I can help.

**Comment by dashng** [comment]
issue occured..
```
Cannot find the C core of igraph on this system using pkg-config.
    We will now try to download and compile the C core from scratch.
    Version number of the C core: 0.7.1.post6
    We will also try: 0.7.1
    
    Using temporary directory: /private/tmp/pip-poSTT7-build/tmp/igraph.qAv4mL
    error: [Errno socket error] [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)
    
    ----------------------------------------
  Rolling back uninstall of python-igraph
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-poSTT7-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lcQ0Ko-record/install-record.txt --single-version-externally-managed --compile --c-core-url=https://github.com/igraph/igraph/archive/master.tar.gz" failed with error code 1 in /private/tmp/pip-poSTT7-build/
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by dashng** [comment]
@ntamas is there docker image with python igraph of development version?

**Comment by ntamas** [comment]
> issue occured..
Apparently your Python and/or the version of OpenSSL on your machine is old and it cannot talk to the server over HTTPS. Googling for the error message shows several similar issues with other projects, all of which probably boil down to installing a newer version of Python and/or OpenSSL. This has nothing to do with igraph yet.

One workaround would be to:

* Download the source code of python-igraph manually from https://github.com/igraph/python-igraph/archive/master.tar.gz
* Download the source code of igraph itself from https://github.com/igraph/igraph/archive/master.tar.gz
* Extract the source code of python-igraph
* Extract the source code of igraph
* Move igraph's source code to a folder named `igraphcore` inside the source code of `python-igraph`
* Run `python setup.py install` from python-igraph's source folder.

This will compile the Python interface as well as the C core and link the two together statically.

**Comment by dashng** [comment]
```
building 'igraph._igraph' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Iigraphcore/include -I/usr/include/python2.7 -c src/arpackobject.c -o build/temp.linux-x86_64-2.7/src/arpackobject.o
In file included from src/graphobject.h:27:0,
                 from src/arpackobject.h:28,
                 from src/arpackobject.c:23:
igraphcore/include/igraph.h:31:28: fatal error: igraph_version.h: No such file or directory
 #include "igraph_version.h"
                            ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```

**Comment by dashng** [comment]
@ntamas god!!! help me.

**Comment by dashng** [comment]
```
running install
running bdist_egg
running egg_info
writing python_igraph.egg-info/PKG-INFO
writing top-level names to python_igraph.egg-info/top_level.txt
writing dependency_links to python_igraph.egg-info/dependency_links.txt
reading manifest file 'python_igraph.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'setup.cfg'
writing manifest file 'python_igraph.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Cannot find the C core of igraph on this system using pkg-config.
Build type: static extension
Include path: igraphcore/include
Library path: igraphcore/lib /usr/local/lib64 /usr/local/lib /usr/lib64 /usr/lib /lib64 /lib
Runtime library path:
Linked dynamic libraries: stdc++
Linked static libraries:
Extra compiler options:
Extra linker options:
building 'igraph._igraph' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Iigraphcore/include -I/usr/include/python2.7 -c src/arpackobject.c -o build/temp.linux-x86_64-2.7/src/arpackobject.o
In file included from src/graphobject.h:27:0,
                 from src/arpackobject.h:28,
                 from src/arpackobject.c:23:
igraphcore/include/igraph.h:31:28: fatal error: igraph_version.h: No such file or directory
 #include "igraph_version.h"
                            ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```

**Comment by dashng** [comment]
@ntamas 

I need a workaround on use DH layout & layout nicely.

My team Insist in believing these two layouts should be better for network with thousands of nodes.

Is it possible python call r-igraph directly.

**Comment by ntamas** [comment]
Re the missing `igraph_version.h` file: this is generated on-the-fly during the bootstrapping of the C core. Try this (note that we are deep in the unsupported hacking territory here, so YMMV):

```sh
cd igraphcore/
./bootstrap.sh
cd ../
python setup.py install
```

Re calling R-igraph: you can try saving your graph from Python into a GraphML file, start an R process using Python's `subprocess` module, load the GraphML file from there, calculate the layout, save it to a text file, and then load the layout from the file into Python again.

**Comment by kpj** [comment]
I wrote a [short script](https://gist.github.com/kpj/fc5570b9ebd77644c49739a340de42db) that downloads/compiles/installs the latest versions (master repository) of igraph and python-igraph.

For completeness, I'll post the most important parts here as well:
```bash
git clone https://github.com/igraph/python-igraph/
cd python-igraph

git clone https://github.com/igraph/igraph igraphcore
cd igraphcore
./bootstrap.sh
mkdir _build && cd _build
../configure --prefix=$PWD/../_install
make
make install
cd -

CPPFLAGS=-I$PWD/igraphcore/_install/include/igraph \
LDFLAGS=-L$PWD/igraphcore/_install/lib \
PKG_CONFIG_PATH=igraphcore/_install/lib/pkgconfig/ \
python3 setup.py install --user
```

Let me know if there are any possible improvements 😇

**Comment by ntamas** [comment]
@kpj thanks for the script and sorry for not responding - this has slipped through the cracks somehow!

@rwst Actually, I wouldn’t mind handing over the project to anyone with the right skills and the right amount of spare time to maintain the project. I am not doing network research any more and lack the time that is needed to prepare releases and take care of things in general. So, if anyone is thinking about a fork — just drop me a message, tell me what your plans would be with the fork, and then we’ll probably work out a solution that does not involve forking.

**Comment by flying-sheep** [comment]
You could also add additional maintainers that don’t take the banner completely, but make the post7 release happen that contain the python-only bugfixes people want.

we could just backport #88, #115, #203, and other stuff and release that version.

**Comment by ntamas** [comment]
@vtraag and I have been exchanging emails since yesterday about some plans to assemble a team that would carry on with releasing updates and keeping things up and running in general. We definitely want to release a new version of python-igraph soon to bring it out of the current limbo state.

One thing that I am considering more seriously now is to adopt the submodule approach that is currently being used in igraph/rigraph, which would simplify things a great deal on the side of the Python interface and would also allow me to decouple the version number of python-igraph from the core igraph library. Let me outline the differences:

* python-igraph does not ship the source code of the C interface; it simply assumes that the C core is either installed somewhere on the user's system in a way that it is discoverable by `pkg-config`, or that it can be downloaded from igraph.org at compile time. This way I am pretty much limited to using the official releases of the C library, and there was no new release of the C library in the last five years or so. The Python interface must also assume that the version of the C library matches the version of the Python interface (so python-igraph 0.7.1 goes hand in hand with igraph 0.7.1).

* In contrast, the repo of the R interface contains a git submodule reference to the repo of the C core library, so it can easily point to any commit within igraph/igraph - no need to depend on an official release.

By doing so in the Python interface, I could get rid of lots of code in `setup.py` that facilitates the detection or the download of the C core library; the released version on PyPI would simply contain the C library as well, and anyone who uses the git repo directly would get the right version of the C library with git's submodule mechanism.

I think that it would probably take less effort to implement this than to backport #88, #115 and other PRs that you mentioned, and then it would allow us to move faster in the future without having to wait for a new release of the C library (although that would be nice, too).

**Comment by flying-sheep** [comment]
Sounds great! It’s always a good move good to not keep a project in limbo when there’s people willing and capable to do maintenance work!

> I think that it would probably take less effort to implement this […]

Really! The mentioned fixed seemed like a handful of 5-liners, so it must be really easy to implement that change :wink:

**Comment by Benfeitas** [comment]
I am also trying to install python-igraph from the github version (as the PyPi has many bugs that were already fixed), by running 

```
pip3 install -U git+https://github.com/igraph/python-igraph.git --install-option="--c-core-url=https://github.com/igraph/igraph/archive/master.tar.gz"
```
(thanks @ntamas for this!)
However, this gives many errors in OSX, where the log ends with:

```
src/graphobject.c:11781:7: warning: implicit declaration of function 'igraph_random_walk' is invalid in C99 [-Wimplicit-function-declaration]
      if (igraph_random_walk(&self->g, &walk, start, mode, steps, stuck)) {
          ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    4 warnings and 20 errors generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/vh/twxllthj78j2bww9v4p_hjx1f3blpf/T/pip-req-build-281dj9c2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/vh/twxllthj78j2bww9v4p_hjx1f3blpf/T/pip-record-orjj5iue/install-record.txt --single-version-externally-managed --compile '--c-core-url=https://github.com/igraph/igraph/archive/master.tar.gz

'" failed with error code 1 in /private/var/folders/vh/twxllthj78j2bww9v4p_hjx1f3blpf/T/pip-req-build-281dj9c2/
```

Is the `error: command 'clang' failed with exit status 1` one of the issues related with what is said in https://github.com/igraph/python-igraph/issues/157#issuecomment-487188859 ? 

I am also going to need to give installation instructions to other people, but while the PyPi installation runs flawlessly and is easy, it comes with all the old bugs :(

**Comment by ntamas** [comment]
We are in the middle of revamping the entire installation process of the Python interface. In particular, we have switched to using git submodules in the Python interface so the repo now "knows" which revision of the C core the Python interface should be compiled against. In the long run, this would ensure that a raw checkout of the Python interface followed by `git submodule update --init` always yields a working tree that contains the "right" version of the C core. (It will probably also mean that we are going to deprecate the `--c-core-url` option and any related hackeries). We would also like to provide pre-built binaries of the Python interface for all supported platforms, but we are not finished with this yet. We expect to make a release some time in September that would fix all these shortcomings and would also come with pre-built binaries.

Weirdly enough, this means that you do _not_ need to pass `--c-core-url` any more as an install option. `pip` is smart enough to recognize that the git repo that it has checked out contains submodules, and will also check out the submodules by running `git submodule update --init --recursive -q`.

**Comment by ntamas** [comment]
Commit 92b1be1e3d0621048a3b30f8c207f663f0134fe1 fixes the issue with `pkg-config`; the vendored igraph repo should now always take precedence over the one discovered by `pkg-config`.

**Comment by Benfeitas** [comment]
Thanks a lot @ntamas , this is very helpful

**Comment by mirekphd** [comment]
`python-igraph` is now among the only 3 remaining exceptions in the whole Kaggle kernels (python docker containers) that still hasn't adopted / moved over to PyPI and requires `conda install' from the `conda-forge` channel? (the other 2 are `basemap` and `proj4`).

**Comment by vtraag** [comment]
@mirekphd, I am not sure what you mean by "hasn't adopted PyPI"? `python-igraph` is available from https://pypi.org/project/python-igraph/. In most cases it should be compiled however, which may make it more difficult to install for many users. However, it should be possible to compile / install in a Docker container.

We are working towards a new release that should also simplify installation. We also plan to release binary wheels for most platforms on PyPI, including Windows. This will take some time though, see also https://github.com/igraph/python-igraph/issues/266#issuecomment-569494201.

**Comment by ntamas** [comment]
python-igraph 0.8.0 is now on PyPI, with precompiled wheels for most platforms and Python versions.

Release notes and an official announcement are coming later, probably on Monday.
