### ISSUE TITLE
How to make the Louvain algorithms  returned a real complete list(community_multilevel)

### ISSUE THREAD

**Issue by juzhichao** [igraph/python-igraph#167]
1. How to make the Louvain algorithms  returned a complete list？not just the modularity from small to large. In other words, make the modularity **from small to large and then to small**?  (if C{True}, the communities at each level are returned in a list but incomplete.)

2. another question, how to make the Louvain algorithms dvided into specific number of community according to the parameters from users

like this:    
def community_multilevel(self, weights, return_levels, **number_community**):

@param number_community: will return the community structures which _len=number_community

**Comment by ntamas** [comment]
> How to make the Louvain algorithms returned a complete list？
You can't; the algorithm stops when the modularity cannot be increased any further by merging or rearranging communities.

> how to make the Louvain algorithms dvided into specific number of community
You can't either; this is not how the algorithm works. You need to use a different algorithm if you want a specific number of communities. Any hierarchical algorithm (i.e. one that produces a dendrogram) would do because you are free to cut the dendrogram when it has reached the desired number of communities.

Also, note that this is not a support forum but a bug tracker. If you have support questions, please send an email to igraph-help@nongnu.org instead.
