### ISSUE TITLE
Graph.Read_GraphML error

### ISSUE THREAD

**Issue by zzzkk** [igraph/python-igraph#172]
I have a problem with reading graphml files (and other e.g. pajek)
Every attempt ends with this message:

> ---------------------------------------------------------------------------
> SystemError                               Traceback (most recent call last)
> <ipython-input-13-00252a08a792> in <module>()
> ----> 1 g = Graph.Read_GraphML("../../data_sample/temp.GraphML")
> 
> SystemError: <built-in method Read_GraphML of type object at 0x000001598920D5E8> returned NULL without setting an error

-  python 3.6
-  Windows 10 (on MacOS is fine)
-  file structure is correct (for sure)
-  python-igraph version: _`python_igraph‑0.7.1.post6‑cp36‑cp36m‑win32.whl`_ (couldn't install with pip because of C core error)

**Comment by ntamas** [comment]
There have been several commits recently that fixed issues related to file handling in Python 3.x; e.g., this one: https://github.com/igraph/python-igraph/commit/f7f612cb2cc812a6e68fd254f5d63cf8f4a3b273 . If you can, please try compiling the Python interface from source.

For what it's worth, the commit mentioned above fixed a problem with file operations in Python 3.x when the operation would have ended with an error (e.g., due to invalid input file format) - basically the C core of igraph signaled an error to the Python interface, but the Python interface failed to convert it into a "proper" Python exception, and that's why you see the message above. If this is the case, a workaround would be to fix the input file. If you cannot compile the Python interface from source now, please upload the input file somewhere and then I'll test it on my machine with the fix.

**Comment by zzzkk** [comment]
Here is some test file (remove *.txt extension)
[sample.graphml.txt](https://github.com/igraph/python-igraph/files/1966879/sample.graphml.txt)
This file was also tested on MacOS and it worked fine

I can't compile from source because of error:

> Cannot find the C core of igraph on this system using pkg-config.
> WARNING: we were not able to detect where igraph is installed on
> your machine (if it is installed at all). We will use the fallback
> library and include pathss hardcoded in setup.py and hope that the
> C core of igraph is installed there.
> 
> If the compilation fails and you are sure that igraph is installed
> on your machine, adjust the following two variables in setup.py
> accordingly and try again:
> 
> - LIBIGRAPH_FALLBACK_INCLUDE_DIRS
> - LIBIGRAPH_FALLBACK_LIBRARY_DIRS
>

**Comment by ntamas** [comment]
The file seems to be okay on my machine as well. Unfortunately I cannot test it further on Windows because I don't use Windows myself and I have no access to Windows machines at all. Someone would need to compile the latest revision of python-igraph on Windows and see if the issue persists there; currently I lack the necessary spare time to do this.

The message that you see above basically explains everything: you would need to compile the C core of igraph first (`python-igraph` is just an interface to the C core, which can be downloaded separately at https://igraph.org), then tell setup.py where the C core was compiled and installed.
