### ISSUE TITLE
How to make colorbar in plot?

### ISSUE THREAD

**Issue by monchin** [igraph/python-igraph#174]
I drew a plot of a graph, as the attributes of each vertex are different, I used `igraph.drawing.colors.RainbowPalette` to differ. Now I would like to add a colorbar or a color legend on the right-bottom corner of the plot to show the lowest and the highest value of the palette. But I didn't find related method in python-igraph. So how could I add colorbar? Thank you very much!

**Comment by ntamas** [comment]
There is no such method, sorry; the plotting subsystem in igraph currently supports drawing graphs only. However, you can get access to the Cairo drawing surface and then use standard Cairo drawing methods to draw anything on top of the figure:

```python
>>> pl = Plot("test.png")
>>> pl.add(g)
>>> surface = pl.surface
>>> type(surface)
<type 'cairo.ImageSurface'>
>>> import cairo
```

Then you need to construct a Cairo drawing context that draws on the surface and call standard Cairo drawing methods on the context object.

Another option is to use `matplotlib` and then make igraph draw the graph on an existing `matplotlib` figure. I have experimented with this a while ago and [summarized my experience](https://stackoverflow.com/a/36154077) on Stack Overflow; this might actually be better in the long run because `matplotlib` offers a fairly complete set of drawing functionality so you don't need to reinvent the wheel.
