### ISSUE TITLE
Bug: return_extened_graph in Sugiyama Layout fails

### ISSUE THREAD

**Issue by anweber85** [igraph/python-igraph#182]
I can get a a sugiyama layout for a graphwithout any problems with:

`layout = g.layout("sugiyama", maxiter = 100)`

and then plot that graph later, however, as soon as I  set return_extended_graph to True

`layout = g.layout("sugiyama", maxiter = 100, return_extended_graph=True)`

I get an error apparently resulting from somewhere in layout.py:
 

>     layout = g.layout("sugiyama", maxiter = 100, return_extended_graph=True)
  File "/usr/lib/python3.6/site-packages/igraph/__init__.py", line 1424, in layout
    l = Layout(l)
  File "/usr/lib/python3.6/site-packages/igraph/layout.py", line 80, in __init__
    self._coords = [list(coord) for coord in coords]
  File "/usr/lib/python3.6/site-packages/igraph/layout.py", line 80, in <listcomp>
    self._coords = [list(coord) for coord in coords]
TypeError: 'Graph' object is not iterable

**Comment by ntamas** [comment]
This is because `return_extended_graph=True` returns the extended graph (as it is implied by its name) and the layout in a tuple. You need to do something like this:

```python
layout, extd_garph = g.layout("sugiyama", ...)
```

and then plot `extd_graph` with the returned layout such that all vertices with index >= `g.vcount()` are plotted with zero size (these are the dummy vertices that were introduced by the layout to make it possible to bend the edges between layers).

**Comment by anweber85** [comment]
In fact, no. Doing as you said gives the exact same mistake, here is the complete error message:

`line 135, in run
    layout, ext_graph = g.layout("sugiyama", maxiter = 100, return_extended_graph=True)
  File "/usr/lib/python3.6/site-packages/igraph/__init__.py", line 1424, in layout
    l = Layout(l)
  File "/usr/lib/python3.6/site-packages/igraph/layout.py", line 80, in __init__
    self._coords = [list(coord) for coord in coords]
  File "/usr/lib/python3.6/site-packages/igraph/layout.py", line 80, in <listcomp>
    self._coords = [list(coord) for coord in coords]
TypeError: 'Graph' object is not iterable
`

**Comment by ntamas** [comment]
Ah, okay. This is because `Graph.layout()` simply forwards the call to a more specific function depending on the first argument, and assumes that the layout method that it will call will return a single layout object only. This does not hold for `Graph.layout_sugiyama()` when `return_extended_graph` is set to `True`. In that case, just call `Graph.layout_sugiyama()` directly:

```python
layout, extd_garph = g.layout_sugiyama(...)
```

**Comment by anweber85** [comment]
Thank you, solved it. 
Actually I am just using this for a workaround because I cannot figure out if the coords list of a sugiyama layout (the one I iterate through when I do `for c in layout`) can contain coordinates of dummy vertices or not.
Is there a definite answer to this?
Thank you again

**Comment by ntamas** [comment]
Yes it can; if your original graph has N vertices, then the first N items of the layout correspond to the original vertices, the rest are the dummies.
