### ISSUE TITLE
Bytes are accepted as vertex name, but lead to `TypeError` in `Graph.add_edges`

### ISSUE THREAD

**Issue by j-i-l** [igraph/python-igraph#196]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

Python version 3.6.5
python-igraph version 0.7.1

Minimal example:

```python
import igraph as ig
g = ig.Graph()
a, b = b'a', b'b'
g.add_vertices([a, b])  
g.vs['name']                                                                                       
Out[6]: [b'a', b'b']  # vertices are added
g.add_edges([(a,b)])                                                                                   
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-daeb7aa29169> in <module>
----> 1 g.add_edges([a, b])
...
TypeError: iterable must return pairs of integers or strings
```

Would be more consistent to assert the correct type of the vertex name already upon creation of the vertex.

**Comment by ntamas** [comment]
I have committed a patch that adds support for `bytes` objects as vertex names.

However, note that there are no strict restrictions on the types of the `name` vertex attribute - you can use any object there because the C core of the library does not treat the `name` attribute in any special way. The Python layer adds a dict-based lookup mechanism that makes it possible to refer to vertices by their names, and _this_ particular mechanism was restricted to strings only (so, in some sense, the library was not incorrect to accept the _creation_ of the vertex with a non-string name).

**Comment by j-i-l** [comment]
This was exactly why the issue was created. 
A solution might also be to not allow `bytes` as vertex names. As long as creation of edges via the `name` vertex attribute is possible whenever creation of nodes with such `name` attribute is possible.
