### ISSUE TITLE
fatal error: igraph_attributes.h: No such file or directory

### ISSUE THREAD

**Issue by testote** [igraph/python-igraph#201]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [ X ] This issue is for the C core of igraph.
- [ X ] This issue is a bug report or a feature request, not a support question.

Trying to install from pip, easy_install and source, I get the same error.

```
[...]
Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
running build_ext
building 'igraph._igraph' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -flto=4 -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I../../build/include -I../../include -I/usr/local/include/igraph -I/usr/include/igraph -I/usr/include/python3.7m -c src/vertexseqobject.c -o build/temp.linux-x86_64-3.7/src/vertexseqobject.o
In file included from src/vertexseqobject.c:26:
src/attributes.h:27:10: fatal error: igraph_attributes.h: No such file or directory
 #include <igraph_attributes.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by ntamas** [comment]
Wild guess since you haven't specified how you installed the C core of the igraph and whether you are trying to compile the head revision of `python-igraph` or the one on PyPI. So, I suspect that you have an older version of the C core of igraph installed in `/usr/local/include/igraph` and `/usr/local/lib`, while you are trying to compile the head revision of the Python interface. Please provide more information if this does not solve your issue, i.e. which version of the C core you have installed and which version of the Python interface you are trying to compile it with.

**Comment by testote** [comment]
Yep my guesses are [still] very wild :bear:  After your helpful answer I installed arpack-3.6.3-1  glpk-4.65-2  igraph-0.7.1-9 using yaourt. The needed files were included on /usr/include/python2.7/ (not /usr/local/include/igraph) and now it works on that version. Maybe including a line specifying these dependencies for Arch on the readme, as libxml2 libxml2-dev are not available, could be useful for the next one here. Let me know if I should push that. Anyway the issue is solved on my opinion. Thanks ntamas.

**Comment by ntamas** [comment]
Unfortunately I'm not familiar with Arch Linux so I'm a bit wary to add any instructions because I won't be able to validate whether it's still up-to-date and I won't be able to respond to any support questions. If you feel so, please send a pull request to the `python-igraph` repo with the proposed modifications and I'll merge it in (with a disclaimer).

**Comment by cuiyan** [comment]
Library path: 
Runtime library path: 
Linked dynamic libraries: igraph
Linked static libraries: 
Extra compiler options: 
Extra linker options: 
building 'igraph._igraph' extension
creating build
creating build/temp.macosx-10.9-x86_64-3.7
creating build/temp.macosx-10.9-x86_64-3.7/src
creating build/temp.macosx-10.9-x86_64-3.7/src/_igraph
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/usr/include/igraph -I/usr/local/include/igraph -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/_igraph/edgeobject.c -o build/temp.macosx-10.9-x86_64-3.7/src/_igraph/edgeobject.o
In file included from src/_igraph/edgeobject.c:25:
src/_igraph/attributes.h:27:10: fatal error: 'igraph_attributes.h' file not found
#include <igraph_attributes.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by szhorvat** [comment]
@cuiyan If you have a problem with python-igraph, please open a new issue and describe what the problem is in clear English and in sufficient detail that we can try to reproduce it.
