### ISSUE TITLE
link to source code of Lattice is inaccurate

### ISSUE THREAD

**Issue by joelmiller** [igraph/python-igraph#204]
I'm trying to find the source code for "Lattice", but when I go to the documentation at https://igraph.org/python/doc/igraph.GraphBase-class.html#Lattice and follow the link to the source code, I end up on a page which has source code, but none of it is for Lattice.

The link should be fixed.  I suspect this is a common issue as I see it for at least a few other methods

- [x ] This issue is for the Python interface of igraph.
- [x ] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
Unfortunately there's not much we can do about that because the documentation is generated by Epydoc; when there is a method that is implemented in C, Epydoc links to the nearest pure Python class that uses this method.

We will probably switch another documentation generation engine in the near future as Epydoc is not maintained any more, so I'm just closing this issue for the time being.
