### ISSUE TITLE
Bidirectional Dijkstra implementation for the igraph

### ISSUE THREAD

**Issue by frasheed** [igraph/python-igraph#209]
- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

Is there any possibility to realize bidirectional Dijkstra with the current version of the igraph? As bidirectional Dijkstra is almost twice fast compared to the ordinary. The NetworkX library has it (see link below).

`https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.weighted.bidirectional_dijkstra.html#networkx.algorithms.shortest_paths.weighted.bidirectional_dijkstra`

I am looking for such feature because in my problem I have sometimes 1 million nodes and 5-7 million edges and then traversing through all nodes is time consuming.

**Comment by ntamas** [comment]
There is no bidirectional Dijkstra implementation in igraph. If you want to gain any speedup with it compared to the current Dijkstra implementation, it would have to be implemented in the C core of the igraph library anyway, so I'm closing the issue here.

If you wish, you can file a feature request in igraph/igraph, although I have to admit that I don't have time for adding new features to the C core so it will be implemented only if someone picks it up and sends me a pull request.
