### ISSUE TITLE
SafeConfigParser has been renamed ConfigParser (Python 3.x deprecation warning)

### ISSUE THREAD

**Issue by ndw** [igraph/python-igraph#215]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

This doesn't appear to have been reported yet:

```
 SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
    self._config = SafeConfigParser()

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

**Comment by ntamas** [comment]
I think it's already fixed in https://github.com/igraph/python-igraph/commit/4507d9aefd2e939fa515815a87b63c905031de9e

**Comment by ndw** [comment]
Ah. Ok. Sorry. It's not in the most recent installed version and I failed to review commits since that release. My bad.

**Comment by ntamas** [comment]
No worries. There were several changes since the last official release but I lack the time to create a "proper" new release (especially because there were changes that followed up API changes in the C core of the library, and there was no official release of the C core either), so there are quite a few issues that are already fixed but not present in the version that you get from PyPI.
