### ISSUE TITLE
Can I install 0.6 on rhel?

### ISSUE THREAD

**Issue by Frostjon** [igraph/python-igraph#217]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [Y] This issue is for the Python interface of igraph.
- [Y] This issue is a bug report or a feature request, not a support question.

I want to use the version 0.6 of python-igraph. But when i used "pip install python-igraph==0.6", I got some error. Is there any way can install 0.6 version?

**Comment by ntamas** [comment]
This is a support question, not a bug report or a feature request. Please send your question to the [igraph-help](https://lists.nongnu.org/mailman/listinfo/igraph-help) mailing list.

(For what it's worth, `pip install python-igraph==0.6` is showing you an error because the installer for 0.6 does not contain the part that automatically downloads the C core of the igraph library. You need to compile and install version 0.6 of the C core first, and then compile python-igraph. Considering the severe issues you have with your compiler environment in #216, I would fix that first instead if I were you).
