### ISSUE TITLE
Non-string vertex names fail to be found

### ISSUE THREAD

**Issue by moof2k** [igraph/python-igraph#22]
As of python-igraph 0.7.1 (73a295e0c4fcb91e66684dd166028bdaf88d9f98 to be specific) it appears giving a vertex a name that is something other than a string doesn't work anymore.

```
import igraph

g = igraph.Graph.Full(3)

g.vs["name"] = ["a", "b", "c"]
print g
print g.vs.find(name="a") # works

g.vs["name"] = [(0, 0), (1, 1), (2, 2)]
print g
print g.vs.find(name=(0, 0)) # fails
```

@ntamas fyi

**Comment by ntamas** [comment]
Non-string vertex names were never supported officially, mostly because most of the Graph methods that accept vertex IDs (e.g., `Graph.degree()`) also accept vertex names, and it would be impossible to decide whether, for instance, a tuple submitted as the first argument to `Graph.degree()` contains a list of vertex IDs or simply refers to the name of a vertex. Actually, the string restriction has been there before; take a look at the source of `igraphmodule_PyObject_to_vid` which is supposed to convert a Python object to an igraph vertex ID; it only supports numbers, strings, `None` and `Vertex`:

https://github.com/igraph/python-igraph/blob/master/src/convert.c#L2299

The modification that you refer to has the purpose of converting calls like `g.vs.find(name="foo")` to `g.vs.find("foo")`. Before this modification, calls like `g.vs.find(name="foo")` simply did a linear scan of all vertices instead of making use of the lookup table for vertex names that igraph maintains behind the scenes, while `g.vs.find("foo")` made use of the lookup table (but disallowed non-string vertex names). The modification makes the behaviour consistent with the rest of igraph.

**Comment by moof2k** [comment]
Thanks for the update @ntamas. It may be worthwhile to add something that throws an exception if you try to set a vertex attribute named 'name' to anything other than a string, maybe?

As a temporary workaround it appears equivalent for us to instead call ``g.vs.select(name="foo")[0].index``.
