### ISSUE TITLE
Vertex names are assigned double datatype when written to disk in graphml format

### ISSUE THREAD

**Issue by neocsbee** [igraph/python-igraph#23]
Here is the header of the graphml file created by write_graphml function:

```
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns
         http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<!-- Created by igraph -->
  <key id="v_name" for="node" attr.name="name" attr.type="double"/>
  <key id="e_wd" for="edge" attr.name="wd" attr.type="double"/>
  <key id="e_weight" for="edge" attr.name="weight" attr.type="double"/>
  <key id="e_sec" for="edge" attr.name="sec" attr.type="double"/>
  <key id="e_mon" for="edge" attr.name="mon" attr.type="double"/>
  <key id="e_year" for="edge" attr.name="year" attr.type="double"/>
  <key id="e_day" for="edge" attr.name="day" attr.type="double"/>
  <graph id="G" edgedefault="undirected">
    <node id="n0">
      <data key="v_name">15110</data>
    </node>
    <node id="n1">
      <data key="v_name">21914</data>
    </node>
    <node id="n2">
      <data key="v_name">1981</data>
    </node>
    <node id="n3">
      <data key="v_name">507</data>
    </node>
```

I would have ideally preferred to see long int for my vertex names, since they are actually integers. They are non-consecutive, though, so string would have been perfect as well instead of double.

I have for the time being tinkered with the graphml file to set the datatypes to correct values. For example, my "wd" attribute is ordinal, so it should be unsigned int. It would be great to have this flexibility in python-igraph.

For some reason, I am not seeing the full output I pasted, so I am attaching the screenshot.
![graphml_alldouble](https://cloud.githubusercontent.com/assets/3037022/6514008/4b3ccf02-c34d-11e4-862f-a89d5834dd67.png)

**Comment by ntamas** [comment]
This is a known limitation of how igraph handles numeric attributes internally. The Python layer of igraph can handle any Python object as an attribute. However, when the Python layer calls the `igraph_write_graph_graphml` function in the C layer, the C layer has to "ask" the Python layer to provide it the values of the attributes in a format that can actually be "understood" by the C layer. Internally, the C layer handles numeric, string and Boolean attributes only - therefore, any Python attribute that contains numbers only are reported to the C layer as being a "numeric" attribute, and the numbers themselves are converted to `double` values in C. This is what gets written into the GraphML file. However, since at this stage we are working with doubles in C only, we can only write `double` as the data type in the GraphML file.

The only solution would be to update the C layer to treat integer and floating point attributes differently.

**Comment by neocsbee** [comment]
Thanks for the explanation.

Perhaps hard by a long shot, but speaking based on the tuplelist function, with which I created the graph, is it possible to send the types of the edge_attrs to be used verbatim in the event of writing the graph in a third-party format?

**Comment by ntamas** [comment]
Most of the writers for third-party formats are in the C layer and the C layer knows nothing about the higher level language in which the C core is embedded, so I cannot do anything about it in the Python interface.

I'm closing the issue now but feel free to keep on commenting if you have additional suggestions.

**Comment by WouterVH** [comment]
if this is not fixed, then there should at least be a way to set the correct data-type on the graph.
Accidentally converting integers to floats is a bug
