### ISSUE TITLE
Prufer encoding available in Python

### ISSUE THREAD

**Issue by Pascal-Ortiz** [igraph/python-igraph#233]
The C library igraph implements a function to encode a tree into a Prufer sequence, cf. [source code](https://github.com/igraph/igraph/blob/c5e9fa195c54e7e10b9a9ccbfc903843ef2c38ea/src/conversion.c#L874).

Is there a Python binding available? It would be great since I have trouble installing the C-library.

**Comment by ntamas** [comment]
Unfortunately there's no Python binding for that function yet. I can add it if you are able to compile the Python interface from source code; otherwise I'll schedule it for the next release, which will be done in parallel to the release of igraph 0.8.0, due some time in August (if everything goes well).

**Comment by Pascal-Ortiz** [comment]
OK, thanks. Finally I got to install the C-version.
