### ISSUE TITLE
Newlines in shorthand notation ("Formula")

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#249]
I was looking at how exactly "formulas" work in the Python interface while trying to make the Mathematica interface both compatible and convenient.

I think it would be reasonable to handle newlines the same way as commas. Currently, newlines do something strange.

Try the following:

```py
ig.plot(ig.Graph.Formula(
    """
    1-2-3
    3-4
    """,simplify=False), vertex_label = range(4))
```

Then try it again, but add a comma before the newline.

The newline seems to behave more like `:` (but it's unclear to me why this happens).

Without comma I get:

![image](https://user-images.githubusercontent.com/1212871/66212196-c5029900-e6bd-11e9-9b99-368e46537e5c.png)

With comma I get:

![image](https://user-images.githubusercontent.com/1212871/66212233-d350b500-e6bd-11e9-9655-bbebae39f193.png)

**Comment by ntamas** [comment]
Actually, the current implementation strips newlines and tabs from the input. The problem is the handling of spaces that are left between `1-2-3` and `3-4` after stripping the newline: the parser parses `"1-2-3 3-4"` as `"1-2-{3,3}-4"` (multiset notation invented just for the sake of getting my point across).

I'm not sure why this happens, but it was probably a bad idea to (ab)use Python's internal tokenizer to parse these expressions. I'll check whether there is an easy fix.

On a somewhat related note, if your input string was `"1-2-3\n3-4"`, that would have been incorrect as well; stripping the newline yields `"1-2-33-4"`, which is isomorphic to what you meant, but the label would be wrong.

**Comment by ntamas** [comment]
There are other bugs in the parser as well; for instance, it breaks if the name of any of the vertices contains a comma, because it first splits around commas and then parses the segments individually.

**Comment by ntamas** [comment]
The bug I mentioned above related to commas in vertex names is not fixed yet; only the usage of newlines in graph formulae. (Although, strictly speaking, this is buggy as well because newlines cannot be used in vertex names at the moment).

**Comment by szhorvat** [comment]
Is there a precise description of a "formula syntax" that should work across different interfaces?

I do not think that we should aim for full consistency. We should aim for some reasonable compromise between consistency and integrating well into the host language (this is why a formula is a string in Python but not in R).

However, it might help to have some guidelines.

**Comment by vtraag** [comment]
Is there any standard for such a "formula syntax" developed already?

I regularly use `tikz`, which also has a graph specification syntax (see https://github.com/pgf-tikz/pgf manual, chapter 19). The syntax can probably not be fully supported, but it might provide a good reference point?

Perhaps there are other such standards that we could follow?

**Comment by ntamas** [comment]
> Is there a precise description of a "formula syntax" that should work across different interfaces?
No, there isn't. The "formula syntax" came in the R interface first, and then I thought it's a good idea for the quick creation of graphs for testing purposes so I implemented something similar in the Python interface.

> Is there any standard for such a "formula syntax" developed already?
I'm not aware of such a standard.
