### ISSUE TITLE
segfault when interacting with a moderately large layout object

### ISSUE THREAD

**Issue by gearmonkey** [igraph/python-igraph#25]
on os x 10.9.5, python 2.7.8, ipython 3.0.0, python-igraph 0.7.1-2

interacting in a variety of ways with a layout object of moderate size (439835 edges, 216943 vertices) is causing a segfault. I encountered the error when trying to serial a layout created with layout_lgl to disc via cPickle. However I have subsequently gotten a segfault under a variety of suspiciously similar circumstances, but with a random layout. I am yet to sucessfully get the object to serialize to disc via any means. See screens for various paths to segfaults.
![image](https://cloud.githubusercontent.com/assets/67409/6866494/cc97f200-d470-11e4-9c7b-50629f49632e.png)
![image](https://cloud.githubusercontent.com/assets/67409/6866533/27021da6-d471-11e4-9942-5197f3762207.png)
![image](https://cloud.githubusercontent.com/assets/67409/6866547/437f3fea-d471-11e4-8f4a-4a1c208ff88a.png)

![untitled](https://cloud.githubusercontent.com/assets/67409/6866693/cce339ca-d472-11e4-9e51-da96dfae5a08.png)

**Comment by ntamas** [comment]
Due to the diversity of the different code paths that all lead to a segfault, I'm suspecting that this is a reference counting error somewhere in the Python interface. I have recently fixed one in the Python interface after the release of 0.7.1-2:

https://github.com/igraph/python-igraph/commit/87aedf88f76e2966b47fb807d66f92c9d4546bc3

Can you try installing python-igraph 0.7.1-4 and check that the bug is still there?

**Comment by gearmonkey** [comment]
Upgraded to 0.7.1-4 and look at that, segfaults are gone. I haven't rerun the lgl layout (as that takes a couple days on this graph) but the random layout seems to be entirely fine now. Thanks!

**Comment by ntamas** [comment]
Great! I'll close the issue for the time being but feel free to reopen if the segfaults come back.
