### ISSUE TITLE
Decompose directed graph

### ISSUE THREAD

**Issue by thosvarley** [igraph/python-igraph#259]
When attempting to decompose a directed graph, the following error is returned:

"InternalError: Error at components.c:469: only 'IGRAPH_WEAK' is implemented, Invalid value"

I have tried every variation on the code: "S = G.decompose(mode="WEAK"/1/"IGRAPH_WEAK" etc.

Make sure that these boxes are checked before submitting your issue -- thank you!

- [X] This issue is for the Python interface of igraph.
- [X] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
These all work for me on my machine, but it could be the case that there was a bug in the latest official release and this is only fixed in the master branch:

```python
>>> g = igraph.Graph.GRG(100, 0.2)
>>> g.to_directed()
>>> g.is_directed()
True
>>> g.decompose()
[<igraph.Graph object at 0x10464c950>]
>>> g.decompose(mode="WEAK")
[<igraph.Graph object at 0x10464ca50>]
>>> g.decompose(mode="weak")
[<igraph.Graph object at 0x10464c950>]
```

This variant should definitely work even in older versions:

```python
>>> from igraph import WEAK
>>> g.decompose(mode=WEAK)
```

Can you please try the variants above first, and if any of them fails, can you repeat the test with the master branch? You can install the master branch with `pip` as follows:

```python
pip install git+https://github.com/igraph/python-igraph#egg=python-igraph
```

(You need a C compiler for this to work).

**Comment by szhorvat** [comment]
This was fixed in the C core and will be part of the next release.
