### ISSUE TITLE
  Strange behavior of Barabasi Albert Graph

### ISSUE THREAD

**Issue by Mbompr** [igraph/python-igraph#26]
Hi, 

I have realised that Barabasi Albert Graph implementation in iGraph has a strange behaviour. The easiest way to see it is by looking at the average degree distribution.

In the simplest case, let's take n=3 and m=1. We should then start with two nodes connected (nodes 0 and 1) and then add a third node (node 2) linked with either 0 or 1 with a probability of 1/2 (because all nodes have the same degree : 1).
Hence if we repeat the graph creation many times we should have, on average:
avg_degree(0) = avg_degree(1) = 3/2 
and avg_degree(2) = 1. 

What has surprised me was to see that this is not what I am observing after doing multiple launches. I rather get 
avg_degree(0) = 5/6
avg_degree(1) = 4/6
and avg_degree(2) = 1

```
import numpy as np
import igraph as ig

n = 3
m = 1

n_launch = 10000

degrees = np.zeros(n)
for _ in xrange(n_launch):
    G = ig.Graph.Barabasi(n, m)
    degrees += G.degree()

print "igraph average degree of nodes 0, 1, 2\t\t", degrees/n_launch

import networkx as nx

degrees = np.zeros(n)
for _ in xrange(n_launch):
    G = nx.barabasi_albert_graph(n, m)
    g_degree = G.degree()
    degrees += np.array([g_degree[i] for i in xrange(n)])

print "networkx average degree of nodes 0, 1, 2\t", degrees/n_launch
```

This snippet returns 
igraph average degree of nodes 0, 1, 2		[ 1.6671  1.3329  1.    ]
networkx average degree of nodes 0, 1, 2	[ 1.4977  1.5023  1.    ]

PS : One could notice that networkx starts with an empty graph and igraph with a complete graph but this does not affect our example here because in both case we have node 0 and 1 connected at t=1, just before we add node 2.

**Comment by ntamas** [comment]
This is probably a bug in the C core of igraph as the Python interface only provides a wrapper to the underlying `igraph_barabasi_game` function. As a workaround, pass `outpref=True` as an argument to `Graph.Barabasi`. The underlying problem is (I think) that the algorithm that generates the graph treats the edges as directed even if the final graph will be undirected, and considers the out-degree of each node only; setting `outpref=True` explicitly forces igraph to use the sum of the out-degree and the in-degree, which fixes the behaviour for undirected graphs.

(@gaborcsardi: I was wondering if it is okay to set `outpref=1` explicitly whenever we generate an undirected graph - I'm not sure whether this was your original intention or not).

**Comment by gaborcsardi** [comment]
> let's take n=3 and m=1. We should then start with two nodes connected (nodes 0 and 1) and then add a third node (node 2) linked with either 0 or 1 with a probability of 1/2 (because all nodes have the same degree : 1).

Why should we start with two nodes connected? We start with a single node only.

**Comment by Mbompr** [comment]
Thank you @ntamas  for your answer, it indeed gives the results I was expecting.

@gaborcsardi What I meant is that, if you start with a single node (node 0) and then add node 1 which should be linked to m=1 other nodes, you will necessarily have at t=1 a graph with two nodes and a link between them.

**Comment by gaborcsardi** [comment]
@Mbompr Yes, but it is a directed link, and BA-game considers in-degrees only.

**Comment by Mbompr** [comment]
@gaborcsardi You are right as this is what igraph implementation does, but this is not what I have seen the most often while looking at papers on BA graph. For example in this paper (https://hal.elte.hu/~vicsek/teaching/biologiai_rendszerek_statisztikus_fizikaja/networks.pdf) by Barabasi and Albert, they write :
![image](https://cloud.githubusercontent.com/assets/1908833/7047850/8d9f36a0-de0f-11e4-98b0-bf596ca50af0.png) where k_j is the degree of node j. Hence at each step the sum of the degree of all nodes increases by 2m while we have added m edges and hence we are working with in and out degrees.

I think both approach exist, but I thought that outpref would be set to True by default.

**Comment by gaborcsardi** [comment]
> I think both approach exist, but I thought that outpref would be set to True by default. If he wants to set it to True, I certainly don't mind.

I see, well, then this is Tamas's business, there are no defaults at the C level...

**Comment by ntamas** [comment]
Okay, what I meant is that the `outpref` parameter does not really make sense for undirected graphs because there are no out-degrees and in-degrees, so it would be better (i.e. less confusing, at least for me) to add something like:

```
if (!directed) {
    outpref = 1;
}
```

in the C code, and document that `outpref` is ignored for undirected graphs. Right now when you generate a graph with `directed=0` and `outpref=0`, igraph still tracks the graph as if it were directed and then drops the arrowheads at the graph creation step.

**Comment by gaborcsardi** [comment]
I see. That makes sense, sure.
