### ISSUE TITLE
GraphBase.community_fastgreedy() may not be working correctly

### ISSUE THREAD

**Issue by Vurgit** [igraph/python-igraph#262]
As is described in the paper "Finding community structure in very large networks" (reference of this function) the author states that the algorithm has the same result as is in the paper "Fast algorithm for detecting community structure in networks",in which the algorithm splits Zachary's "karate club" GML data into 2 groups and NCAA football GML data into 6 groups.When applying community_fastgreedy to "karate club" data the algorithm splits it into 3 groups instead of 2; when applying it to NCAA footaball teams data the results seem to be the same as those in the paper. I suspect there might be some mechanism error whithin the algorithm, could it be?

**Comment by ntamas** [comment]
It's very unlikely; this issue has been brought up before a few times on the mailing lists (years ago). The bottom line is that the original descripton of the algorithm does not define how it should deal with ties, i.e. situations where there are two or more possible steps that would yield exactly the same amount of increase in modularity. Implementations typically choose one or the other in a fairly arbitrary way, and in some cases this could lead the algorithm down a path that ends up with more communities in the end than the other possible paths.

Another problem is numeric instability; ties are not always recognized by implementations because of the way they calculate modularity scores. There could be situations when two options lead to an equal increase in modularity, but due to the inaccuracy of floating-point calculations, one of the steps looks more advantageous by a tiny margin; in that case, the implementation will deterministically choose this path. It could even happen that the same implementation on two different machines with different operating systems or different underlying hardware architecture will yield different results.

**Comment by Vurgit** [comment]
Thank you for your answer, Mr Nepusz. It seems that every time I run this algorithm on my machine the results turn out to be the same, does it mean Python deals with ties the same way every time? Another weird thing is that it has the same dendrogram output and the same maximum modularity as I do in MATLAB,so the cutoff position on the dendrogram tree should be the same ,resulting in the same results as in MATLAB theoretically. Different results than in MATLAB is really confusing. And does it mean that the comunity_fastgreedy algorithm is not that stable? Is there any more stable algorithm in igraph, like community_multilevel()? Thank you for your time and patience.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tamás Nepusz"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月13日(星期五) 晚上11:00
收件人:&nbsp;"igraph/python-igraph"<python-igraph@noreply.github.com&gt;;
抄送:&nbsp;"yangyang"<980182570@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [igraph/python-igraph] GraphBase.community_fastgreedy() may not be working correctly (#262)




It's very unlikely; this issue has been brought up before a few times on the mailing lists (years ago). The bottom line is that the original descripton of the algorithm does not define how it should deal with ties, i.e. situations where there are two or more possible steps that would yield exactly the same amount of increase in modularity. Implementations typically choose one or the other in a fairly arbitrary way, and in some cases this could lead the algorithm down a path that ends up with more communities in the end than the other possible paths.
 
Another problem is numeric instability; ties are not always recognized by implementations because of the way they calculate modularity scores. There could be situations when two options lead to an equal increase in modularity, but due to the inaccuracy of floating-point calculations, one of the steps looks more advantageous by a tiny margin; in that case, the implementation will deterministically choose this path. It could even happen that the same implementation on two different machines with different operating systems or different underlying hardware architecture will yield different results.

**Comment by ntamas** [comment]
> It seems that every time I run this algorithm on my machine the results turn out to be the same, does it mean Python deals with ties the same way every time?

Yes; there is no randomization built into the algorithm. There are other sources of randomness, though; different versions of Python or the same version on different machine architectures _could_ lead to differences. (I'm not saying that it _will_, only that it _could_). Or, different implementations of the algorithm (i.e. the one in `igraph`, the one in `networkx`, a third one in MATLAB etc) could treat the ties differently, and this could also lead to different results. (Again, I'm not saying that it _will_, only that it _could_).

> Different results than in MATLAB is really confusing.

Sorry, but it's not enough to start investigating further. You need to give us a small, self-contained, reproducible example that produces an incorrect result, and tell us what the correct result should be.

> And does it mean that the comunity_fastgreedy algorithm is not that stable?
It is "stable" in the sense that it always gives the same result on the same machine with the same implementation of Python and igraph when executed multiple times. It does not mean that it gives the same result as any alternative implementation since the algorithm is not fully specified - it leaves it up to the implementation to deal with ties somehow. And even if it did, since the algorithm is dealing with floating-point numbers and [floating-point arithmetics is not precise](https://www.itu.dk/~sestoft/bachelor/IEEE754_article.pdf), it can never be fully guaranteed that it yields the same result with any C compiler on every possible CPU architecture.

**Comment by Vurgit** [comment]
Thank you very much for your answer, Mr Nepusz. I have a few more questions that I would like to consult you. I am trying to build a undirected-weighted graph using Weighted_Adjacency() function, say, I built a weighted adjacency matrix like this:


import numpy
import igraph
adj = numpy.random.random(size=[4,4]) # a random undirected weighted graph
adj=list(adj)
g = igraph.Graph.Weighted_Adjacency(adj,attr="weight",mode=igraph.ADJ_UNDIRECTED)

rint g.is_weighted()
print g.es["weighted"]



(i,j) in adj means the weight between node i and j in graph g.It seems that the output of is_weighted() function is true,while error report says there is no attribute g.es["weighted"]. Is it really a weighted graph as I expected? When I apply algorithms like community.fastgreedy() or so to graph g will it cope with g as a weighted graph?Thank you for your patience and time.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tamás Nepusz"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月13日(星期五) 晚上11:38
收件人:&nbsp;"igraph/python-igraph"<python-igraph@noreply.github.com&gt;;
抄送:&nbsp;"yangyang"<980182570@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [igraph/python-igraph] GraphBase.community_fastgreedy() may not be working correctly (#262)



 
It seems that every time I run this algorithm on my machine the results turn out to be the same, does it mean Python deals with ties the same way every time?
  
Yes; there is no randomization built into the algorithm. There are other sources of randomness, though; different versions of Python or the same version on different machine architectures could lead to differences. (I'm not saying that it will, only that it could). Or, different implementations of the algorithm (i.e. the one in igraph, the one in networkx, a third one in MATLAB etc) could treat the ties differently, and this could also lead to different results. (Again, I'm not saying that it will, only that it could).
  
Different results than in MATLAB is really confusing.
  
Sorry, but it's not enough to start investigating further. You need to give us a small, self-contained, reproducible example that produces an incorrect result, and tell us what the correct result should be.
  
And does it mean that the comunity_fastgreedy algorithm is not that stable?
 It is "stable" in the sense that it always gives the same result on the same machine with the same implementation of Python and igraph when executed multiple times. It does not mean that it gives the same result as any alternative implementation since the algorithm is not fully specified - it leaves it up to the implementation to deal with ties somehow. And even if it did, since the algorithm is dealing with floating-point numbers and floating-point arithmetics is not precise, it can never be fully guaranteed that it yields the same result with any C compiler on every possible CPU architecture.

**Comment by ntamas** [comment]
> report says there is no attribute g.es["weighted"].

The attribute is called `weight`, not `weighted`.

> When I apply algorithms like community.fastgreedy() or so to graph g will it cope with g as a weighted graph?

Most igraph functions have a keyword argument named `weights`; you need to provide the name of the edge attribute that you want to treat as weights there. E.g.

> g.community_fastgreedy(weights="weight")

Also, please note that this is an issue tracker, not a support forum. If you have support questions, please send them to igraph-help@nongnu.org instead.
