### ISSUE TITLE
canonical labels for colored graph

### ISSUE THREAD

**Issue by eendebakpt** [igraph/python-igraph#27]
For colored graphs the canonical labeling does not work (this is supported by bliss I believe). An example script is included below. The last canonical labeling printed is [3, 1, 2, 0], but this does not respect the coloring.

```python
import igraph
g = igraph.Graph()
for ii in range(4):
    g.add_vertex()

print( g.canonical_permutation() )
g.add_edge(0,0)
g.add_edge(2,2)

print( g.canonical_permutation() )

g.vs[0]['color']=0
g.vs[1]['color']=0
g.vs[2]['color']=1
g.vs[3]['color']=1

print( g.canonical_permutation() )
```

**Comment by ntamas** [comment]
The canonical permutation algorithm in igraph was never meant to take the coloring into account; check the signature and the documentation of the corresponding function in the C core:

http://igraph.org/c/doc/igraph-Isomorphism.html#igraph_canonical_permutation

Note that the colors are not passed to `igraph_canonical_permutation` in the C layer, and neither they are in `igraph_isomorphic_bliss`. Vertex and edge coloring is supported only in `igraph_isomorphic_vf2` (i.e. by the VF2 algorithm). I'm not sure about the reason for this, maybe the C core is using an older implementation of BLISS that did not support colors at that time. Anyway, if you would like to see this implemented in igraph in the upcoming versions, please file a bug report into the "main" igraph repo at https://github.com/igraph/igraph/issues because it has to be implemented in the C layer.
