### ISSUE TITLE
function to find out if vertex is part of a cycle

### ISSUE THREAD

**Issue by LivC182** [igraph/python-igraph#278]
Hi,
Sorry to bother you, I need to check if certain vertexes are part of a cycle: if there is a non-zero path from vertex_x to itself. Since all the functions that calculates paths only return the shortest one, i cannot use them. 

Is there any function I can use for my issue ? 

Best, 
Liviu

**Comment by szhorvat** [comment]
Please direct support questions to the support forum: https://igraph.discourse.group/ 

This is the issue tracker. It is meant for bug reports and feature requests, not for support.

**Comment by ntamas** [comment]
I assume that your graph is directed (since in an undirected graph the problem is trivial: if there is at least one edge incident on the vertex, you can traverse that edge and come back on the same edge, making the walk a cycle).

So, in a directed graph, find the strongly connected components of the graph, and check which component your vertex falls into. If the component of your vertex is of size >= 2, your vertex is part of at least one cycle.

E.g.:

```python
>>> g=igraph.Graph.Formula("A-->B-->C-->D-->B, D-->E")
>>> list(g.clusters(mode="strong"))
[[0], [1, 2, 3], [4]]
```

This tells you that vertices 0 and 4 (i.e. "A" and "E") are not part of any cycles.

---

For what it's worth, we wish to reserve the issue tracker on Github for genuine bug reports, not support questions. If you need help using igraph, please use our [Discourse group](https://igraph.discourse.group)

**Comment by szhorvat** [comment]
> can traverse that edge and come back on the same edge, making the walk a cycle

To be precise, that is not the definition of an undirected cycle. It is usually required for a cycle to have no repeated edges.

But one can do this: find a neighbour of the vertex so that if we remove the edge between them, then the vertex and the neighbour will still be in the same connected component. If so, there is an undirected cycle.

**Comment by szhorvat** [comment]
In IGraph/M I have a function which I believe basically solves this problem for undirected graphs. It looks for parts of the graph which are trees, and it does this by starting at the leaves and repeatedly removing them until no leaves are left.

It is these "tree-like components" that have no cycles going through them. Here's an example:

![image](https://user-images.githubusercontent.com/1212871/74183389-2545b080-4c45-11ea-955c-45dce1dec40c.png)

I could contribute this to the C core at some point.
