### ISSUE TITLE
Make plotting dependencies optional

### ISSUE THREAD

**Issue by buhrmann** [igraph/python-igraph#283]
Hi, not sure how dependencies are handled here, or who is responsible for the binary conda packages, but installing igraph from conda-forge also installs cairo, matplotlib etc. Would it be possible to not install these by default?

**Comment by vtraag** [comment]
This [repository](https://github.com/conda-forge/python-igraph-feedstock ) contains the details for the build for `conda` from the `conda-forge` channel. There is no dependency on `matplotlib`, so presumably you installed something else that triggers the installation of `matplotlib`. The only package that is installed is `pycairo`, but `conda` does not support optional dependencies, as far as I know (if you think otherwise, perhaps you can provide a reference).

We also provide binary wheels on PyPI, which does not have a dependency on `pycairo`, so you can simply decide to install `pycairo` yourself or not. Installing `pycairo` is not entirely straightforward and requires external (i.e. non-Python) libraries (namely `cairo`). This is why it is not a dependency on PyPI. `conda` on the other hand also handles such external (i.e. non-Python) libraries, and so installation of `pycairo` is straightforward on `conda`.

**Comment by buhrmann** [comment]
Thanks for the quick response! You're right. Matplotlib must be an indirect dependency of some other package. As for pycairo, I guess one could just not include it in the conda-forge wheels, and require the user to install it manually, same as the PyPI version. I understand it's easier for most people if it's included. On the other hand, in a containerized production environment it adds a bit of overhead:

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cairo-1.16.0               |    hfb77d84_1002         1.5 MB  conda-forge
    fontconfig-2.13.1          |    h86ecdb6_1001         340 KB  conda-forge
    gettext-0.19.8.1           |    hc5be6a0_1002         3.6 MB  conda-forge
    glib-2.58.3                |py37h6f030ca_1002         3.3 MB  conda-forge
    gmp-6.2.0                  |       he1b5a44_2         811 KB  conda-forge
    libiconv-1.15              |    h516909a_1005         2.0 MB  conda-forge
    libuuid-2.32.1             |    h14c3975_1000          26 KB  conda-forge
    libxcb-1.13                |    h14c3975_1002         396 KB  conda-forge
    libxml2-2.9.10             |       hee79883_0         1.3 MB  conda-forge
    pcre-8.44                  |       he1b5a44_0         261 KB  conda-forge
    pixman-0.38.0              |    h516909a_1003         594 KB  conda-forge
    pthread-stubs-0.4          |    h14c3975_1001           5 KB  conda-forge
    pycairo-1.19.1             |   py37h438ddbb_0          77 KB  conda-forge
    python-igraph-0.8.0        |   py37h9e3b1fc_0         2.1 MB  conda-forge
    texttable-1.6.2            |             py_0          15 KB  conda-forge
    xorg-kbproto-1.0.7         |    h14c3975_1002          26 KB  conda-forge
    xorg-libice-1.0.10         |       h516909a_0          57 KB  conda-forge
    xorg-libsm-1.2.3           |    h84519dc_1000          25 KB  conda-forge
    xorg-libx11-1.6.9          |       h516909a_0         918 KB  conda-forge
    xorg-libxau-1.0.9          |       h14c3975_0          13 KB  conda-forge
    xorg-libxdmcp-1.1.3        |       h516909a_0          18 KB  conda-forge
    xorg-libxext-1.3.4         |       h516909a_0          51 KB  conda-forge
    xorg-libxrender-0.9.10     |    h516909a_1002          31 KB  conda-forge
    xorg-renderproto-0.11.1    |    h14c3975_1002           8 KB  conda-forge
    xorg-xextproto-7.3.0       |    h14c3975_1002          27 KB  conda-forge
    xorg-xproto-7.0.31         |    h14c3975_1007          72 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        17.6 MB
```

But again, I understand if you want to keep including it as a convenience for the majority of people.

**Comment by ntamas** [comment]
@vtraag Have you tried depending on `cairocffi` instead of `pycairo`? As far as I know, they are API-compatible, but maybe the overhead of `cairocffi` would be smaller.

Another thing that we could try is to package `python-igraph` in the official packages with `plotting` as an "extra". This way one could run `pip install python-igraph` to get the vanilla Python interface without the plotting dependencies, or `pip install python-igraph[plotting]` to get `python-igraph` _and_ all the dependencies that are needed for plotting (i.e. `pycairo` or `cairocffi` at the moment). Is this syntax supported by `conda-forge`?

**Comment by vtraag** [comment]
We could do that for the PyPI version indeed, that might be nice!

For conda it seems in development (see https://github.com/conda/conda/issues/1696) but the version 4.4 quoted there is not released (yet).

I'll look into whether `cairocffi` has a lower overhead. But it seems that `pycairo` is not a really big overhead compared to the overall size.

**Comment by ntamas** [comment]
`pycairo` brings in `cairo`, `fontconfig`, `gettext`, `glib` and all the `xorg-*` packages as well if I am not mistaken.

**Comment by vtraag** [comment]
Yes, that is true of course, I only considerd `pycairo` and `cairo`. But `cairocffi` will of course also bring in `cairo`, which will bring in the other packages. In fact, `cairocffi` will also bring in two extra dependencies, namely `cffi` and `pycparser`. So I don't see any reason to switch to `cairocffi`.

**Comment by ntamas** [comment]
Okay, then the question remains: would it make sense to declare a `plotting` "extra" in `setup.py`? Would that make it possible to allow users to simply install `python-igraph` in Anaconda without bringing in all the extra dependencies and install `python-igraph[plotting]` if they also need the plotting functionality?

(We could also name it `[all]`, `[full]` or any other name of course).

**Comment by vtraag** [comment]
> Okay, then the question remains: would it make sense to declare a plotting "extra" in setup.py?

Yes, that makes sense, but it will only work when installing using `pip`.

In order to make it work on `conda`, we would need to have two separate packages. We would then have something like `python-igraph-base` and `python-igraph`, where the `python-igraph-base` would not install the `pycairo` library. This is also how this problem is approached for `matplotlib`, for which conda provides the [`matplotlib-base`](https://anaconda.org/conda-forge/matplotlib-base/files) package, which installs `matplotlib` but not the Qt backend (if memory serves me well). This is the best possible solution I think within the `conda` environment.

**Comment by ntamas** [comment]
How does that sound @buhrmann? Would that solve the problem for you?

**Comment by buhrmann** [comment]
Sure, sounds good to me! But again, don't create any extra work for yourselves on my account. I was just trying to find out if there already was a way to limit dependencies somehow. I was cleaning up some docker images we use internally, and which get built several times a day, so the smaller the better. Any improvements in that direction would be nice-to-haves...

**Comment by vtraag** [comment]
OK, good, let's do that then. In principle it is quite straightforward for `conda`, it just requires a copy of the `python-igraph` feedstock that excludes the `pycairo` dependency. I will see when I will get around to the `conda` feedstock. Probably best to do that after we close https://github.com/conda-forge/python-igraph-feedstock/issues/22. Will you update `setup.py` @ntamas ?

**Comment by ntamas** [comment]
`setup.py` updated. I have chosen the last minor version of `pycairo` that still supports Python 2.7.

**Comment by vtraag** [comment]
I decided to no longer include `pycairo` as a dependency in the `conda-forge` build from version 0.9.1 onwards, and users should install it separately indeed. It is also a bit strange to have a separate build for this just for the sake of the dependency, people should just be able to install it indeed if necessary.

@ntamas, in order to avoid future questions around the ["Plotting not available"](https://github.com/igraph/python-igraph/issues/129) error, perhaps we can suggest in the error that `pycairo` or `cairocffi` should be installed?
