### ISSUE TITLE
Speed differences dict vs igraph attribute query

### ISSUE THREAD

**Issue by p-ortmann** [igraph/python-igraph#287]
Hi everyone,
I am looking at using i-graph for some numerical schemes on graphs related to traffic and ran into the following oddity: access times of edge attributes in igraph is significantly slower than pythons standard dicts, could someone clarify what I am doing wrong here?
![image](https://user-images.githubusercontent.com/60644683/77296531-1cd2a200-6ce8-11ea-8fd8-109a8552ef40.png)
edit: to level the playing field, I get similar results with a nested dict:
![image](https://user-images.githubusercontent.com/60644683/77297163-2c061f80-6ce9-11ea-8bc1-132140f5a952.png)

**Comment by ntamas** [comment]
There's probably an additional overhead associated to `g.es[1]`, which constructs a throwaway `Edge` object. These objects do not have a permanent existence because the underlying C library does not have such a concept -- `Edge` objects are provided purely by the Python interface to provide a more intuitive proxy to the underlying edge attributes.

Try doing this instead:

```
flow_values = g.es["flow"]
%timeit flow_values[1]
```

This should be fast as it is a simple list indexing operation.

**Comment by p-ortmann** [comment]
Makes sense, thanks!
