### ISSUE TITLE
igraph.bfs

### ISSUE THREAD

**Issue by ElemenT5ven** [igraph/python-igraph#298]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [X] This issue is for the Python interface of igraph.
- [ ] This issue is a bug report or a feature request, not a support question.
Hello, 

We are currently trying to get generate a spanning tree from a graph by using a bfs.
So we are adding edge using the vertex ids visited and the parent of every vertex in the BFS
However we got some strange result in the parent array. For example, in our tree we have 2 vertex connected to a vertex, who has only one edge in the original graph
Here is the an example of our issue in a notebook in a repository git:
https://github.com/ElemenT5ven/testBFS

Thank you!

**Comment by ntamas** [comment]
This is a support question, not a bug report or a feature request (as you indicated by un-ticking the second box). Next time please ask your question in the [igraph Discourse group](https://igraph.discourse.group); the issue tracker is reserved for genuine bug reports and feature requests.

Anyway, you are misinterpreting the parent array. The i-th element of the parent array is the ID of the parent vertex of the vertex with ID _i_. For instance, the element at index 3 in the parent array is zero because vertex 3 was visited from vertex 0. The ordering of items in the parent array has nothing to do with the order of the BFS traversal -- it is ordered according to numeric vertex IDs.
