### ISSUE TITLE
Shortest paths: Accumulating "extra" information from selected edge attributes?

### ISSUE THREAD

**Issue by HTenkanen** [igraph/python-igraph#337]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

Hi!

And first of all thanks for the great work with this library 💪 

I am interested whether it would be possible to add a feature to python-igraph / igraph that would allow to accumulate extra information from the shortest paths? A typical use case for this relates to transport network analysis where I want to find the shortest path between two locations (nodes) using e.g. travel time as weight, but at the same time I want to know what was the traveled distance between those nodes (or some other accumulative information). Hence, I would like to accumulate extra information from the path(s) based on other (numeric) edge attributes that are part of the same graph. 

Does this sound like something that could be implemented? In principle, this sounds like quite a trivial thing to do, but naturally I am not too familiar with the internals to fully understand whether this is the case. 

I am currently developing a Python library where I would need something like this, and preferably I would want to build something on top of existing network libraries (preferably python-igraph as it is fast 🙂) instead of starting from scratch, hence, the question. 

Best,
Henrikki

**Comment by szhorvat** [comment]
Can you explain why you cannot compute this with the current available tools? For simple graphs, it should be possible.

**Comment by szhorvat** [comment]
@ntamas It would probably be useful to have functions which return not the list of vertices, but the list of edges that make up a shortest path. Having the edge indices directly available would make as OPs task easier.

More importantly, if the graph contains multi-edges, it is not possible to tell which of a set of parallel edges belongs to the shortest path. When the graph is weighted, it will be one specific edge out of all the parallel ones. Generally, if the function returns a list of edges, they can be converted back into a list of vertices, but not vice versa. Even converting from vertices to edges is not entirely trivial because one must always choose "the other" endpoint of undirected edge---but at least it's possible. Thus, ideally, the result would be made available both in terms of vertices and edges.

**Comment by vtraag** [comment]
Note that in [`get_shortest_paths`](https://igraph.org/python/doc/igraph.GraphBase-class.html#get_shortest_paths) you can indicate that you want edge indices to be returned (`output = 'epath'`), so I believe this is already implemented.

**Comment by HTenkanen** [comment]
@vtraag Ah, awesome! Was reading the docs yesterday but somehow missed this small piece of important information! Thanks a lot for pointing this out! 🙏  I think this should do exactly what I was looking for. 🙂
