### ISSUE TITLE
What does community_leading_eigenvector() do?

### ISSUE THREAD

**Issue by davdavsen** [igraph/python-igraph#35]
I have been having trouble with the community_leading_eigenvector() function. I am not allowed to share the data I am working on yet, but I hope I can get some help anyway.

My troubles are:
Problem number 1: For networks bigger than about 8000 nodes the algorithm returns splits with very low modularity compared to other algorithms. The weird thing is that the bigger the network, the fewer communities are created (my networks range from 1000-16000 in size with an average degree of about 3 and are unweighted and undirected). The biggest network gets only one cluster from leading_eigenvector(). When I run the algorithm in Mathematica, even the big networks can be partitioned using leading_eigenvector.

These are my results for leading_eigenvector and infomap for comparison (some of the axis labels are swapped around - I am sorry about that)
![nr_communities_lead_eig](https://cloud.githubusercontent.com/assets/13002803/8286092/7a3f016e-18ff-11e5-9d7c-824390848a11.png)
![modularity_lead_eig](https://cloud.githubusercontent.com/assets/13002803/8286099/8a9c6ae2-18ff-11e5-9b0c-b1e1ef2959c8.png)

![nr_communities_infomap](https://cloud.githubusercontent.com/assets/13002803/8286105/94816a1c-18ff-11e5-8d0f-4aeaa3d749a9.png)

![modularity_infomap](https://cloud.githubusercontent.com/assets/13002803/8286103/9132ded6-18ff-11e5-8d3c-ed3af8e83f7f.png)

Problem number 2: When I use the "clusters = ..." to decide for the algorithm how many clusters should be created, it does not always oblige. It often does, but then every now and then it creates a split with 9 clusters, even though I asked for 11, and the optimal partition has 23. I ran the following script

optimalcluster = g.community_leading_eigenvector()
print len(optimalcluster)
for i in range(30):
   clustered = g.community_leading_eigenvector(clusters= i+1)
   print len(clustered)

And it produced
23
1
2
3
4
5
6
7
8
9
9
9
10
11
12
13
14
15
16
16
16
16
16
16
16
16
16
16
16
17
18

**Comment by ntamas** [comment]
Re problem 1: it is probably some kind of a bug in the ARPACK eigenvector solver or the way we use it. (If you check the source code of `igraph_community_leading_eigenvector` in `community.c`, you can see that we perform quite a few hacks to make the eigensolver more stable for certain pathological cases, but it could be the case that this is not enough). Also, when igraph decides whether a certain coordinate of an eigenvector is positive or negative, small eigenvector coordinates with an absolute value less than 1e-8 are replaced with zero to counteract the effect of numerical instability. It could be the case that Mathematica does not do this and hence proceeds with splitting communities even if igraph stops at a certain point.

Unfortunately I cannot proceed any further without getting an example graph on which I could reproduce the problem and a corresponding trace of the algorithm from Mathematica to see where the cuts are supposed to happen according to Mathematica.

Re problem 2: the number of clusters that you specify is actually the *maximum* number of clusters. igraph will stop earlier if it is not able to split the communities any further (because all the coordinates of the leading eigenvector have the same sign).
