### ISSUE TITLE
Get All Simple Paths from a graph, without high memory usage

### ISSUE THREAD

**Issue by Luxxii** [igraph/python-igraph#366]
Hi everyone, 

the current implementation of `get_all_simple_paths`  [provided here](https://github.com/igraph/python-igraph/blob/2332e35922763253b4e3a656045e230a13f3eb95/src/igraph/__init__.py#L845) currently fills a list with all simple paths, which are stored in memory. 

In my case: The generated graphs do have to many simple paths between `src`and `dst`, so that it cannot fit anymore in memory. It is unclear to me whether the filling of the list causes the high memory usage, or the underlying implementation of `_get_all_simple_paths`.

I could increase the swap in linux systems to counter this, but this would only work until a more complex graph is processed. Another solution would be to use a generator by traversing the graph via python:

```python
def _get_all_simple_paths(graph, start, end):
    path  = []
    queue = [(start, end, path)]
    while queue:
        start, end, path = queue.pop()
        path = path + [start]

        for node in set(graph.neighbors(start,mode='OUT')).difference(path):
            queue.append((node, end, path))

        if start == end and len(path) > 0:              
            yield path
```

Unfortunately, the generator approach is very slow, compared to the `get_all_simple_paths` implementation provided here. 

I wanted to ask, if it would be possible to extend the functionality of `get_all_simple_paths` to also return a generator, which could be used instead. It would be great if such a approach would be faster, then my current "manual" traversal (see snippet)

Would such a generator be even possible with the underlying: `self._get_all_simple_paths(v, to, cutoff, mode)`-implementation?

---

I am not sure whether to report this as an issue (due to the high memory consumption) or as a feature request (implementation of a generator for `get_all_simple_paths`).

**Comment by szhorvat** [comment]
> It is unclear to me whether the filling of the list causes the high memory usage, or the underlying implementation of `_get_all_simple_paths`.

The reason why it uses a lot of memory is that there are lots of paths.

> Would such a generator be even possible with the underlying: `self._get_all_simple_paths(v, to, cutoff, mode)`-implementation?

No, this would require a rewrite of the underlying C function, in such a way that it is still useful and usable for other languages than Python.

However, I do agree with you that what they call a "generator approach" in Python is probably the best solution for any combinatorial enumeration problem. We discussed this before. Unfortunately, implementing it is usually not trivial (e.g. one needs an explicit stack for recursive algorithms).

A simpler (but IMO not as good) approach that some other igraph functions use is to employ a callback function that is called for every object (in this case: every path) that is found, and can indicate that the enumeration should be stopped. The drawback compared to "generators" is that once the enumeration is stopped, it cannot be resumed, only restarted from the beginning.

**Comment by ntamas** [comment]
I think the question here for the OP should be: would it be useful for you if we provided a callback-function-like approach? This is relatively easy to do in the underlying C library (although chances are we won't be able to make it before the next release, scheduled for next week). It would look something like this:

```
def func(path):
    # do whatever you want with the path here, e.g.:
    print(path)
    # return True to cancel the iteration, any falsy value to keep on iterating
    return len(path) > 10

graph.for_all_simple_path(func)
```

The above example would keep on iterating the paths and stop as soon as the first path that is longer than 10 vertices is returned.

**Comment by szhorvat** [comment]
The reality is that if you run out of memory with this, then you will likely also run out of time trying to process all paths. Either the callback or the generator approach would be practically useful only if it would be acceptable for your application to terminate the enumeration early.

**Comment by Luxxii** [comment]
@ntamas @szhorvat  The python implementation is only an example on how i would solve it currently. A callback function would be sufficient, as long as entries can be skipped (e.g.: skip paths longer than `x`. A stopping at the first occurrence of a path of length `x` would not be sufficient. But @ntamas example could be modified accordingly). Such a callback would be great, especially when its more efficient. It would be interesting if paths then can be returned sorted by a criterion (e.g.: length).

@szhorvat Yes and no. It is possible for DAGs to calculate the total amount of simple paths in an efficient manner, therefore calculate the needed amount of memory.  It is even possible to calculate the number of simple paths for a fixed length `x` (or other criterions) for a `src`and `dst` node. In my use-case: I process attributes of nodes and edges which are in a simple path (-> ordered) and want to save such information in a database. Databases usually do have large disk space, larger then main memory (+ swap) on other or multiple systems, which is the reason why i would like to use such a "generator approach". I would like to fill the database (almost all of the disk space).  I hope my problem is clear now.

**Comment by ntamas** [comment]
> A callback function would be sufficient, as long as entries can be skipped

To put things into context, this is the [current implementation](https://github.com/igraph/igraph/blob/develop/src/paths/simple_paths.c#L65) in C. The path is added to the result vector [here](https://github.com/igraph/igraph/blob/develop/src/paths/simple_paths.c#L149). This part of the code could be replaced with a call to a callback function that returns a boolean. The question is what to do if the user wants to stop.

One thing that we could do is to exit immediately, but it looks like this won't suffice because it would terminate the search completely. Another thing that we could do is to pretend that the vertex has no more neighbors that could be visited (i.e. that all neighbors of the vertex are already part of the current path). This would let the function backtrack and continue exploring other paths.

Note that if you simply want the search to backtrack when the function reaches paths of a given length, then you can use the `cutoff` argument of `get_all_simple_paths()`. Would that work for you @Luxxii, or do you have a more complex stopping (backtracking) condition?

> It would be interesting if paths then can be returned sorted by a criterion

I'm afraid that's not easy to do; the current implementation is essentially an (optionally depth-limited) DFS so the order in which you get the results depends on the order of the DFS traversal.

**Comment by Luxxii** [comment]
> The path is added to the result vector here

I observed during experimenting that the `self._get_all_simple_paths()`method (the C implementation) returns a vector with results separated by `-1`.  Currently it would be sufficient to stop and retrieve all paths which reaches an length up to `x`. So a callback at this point would be great, instead of appending/returning a large vector.

> Another thing that we could do is to pretend that the vertex has no more neighbors that could be visited (i.e. that all neighbors of the vertex are already part of the current path). This would let the function backtrack and continue exploring other paths.

Would this not allow the user to decide on how to search the graph for constrained simple paths? Or how far he wants to explore one path before exploring other paths? In future, i may need a more complex condition and would appreciate such a behavior. Currently i can evade this (to some degree) by modifying the graph specifically, mapping the complex condition to the length of the path. For this we could provide multiple return values e.g.: `-1` for backtracking and/or `0` for stopping (enum-like). 

> Note that if you simply want the search to backtrack when the function reaches paths of a given length, then you can use the cutoff argument of get_all_simple_paths(). 

I currently utilize the `cutoff` in `get_all_simple_paths()`. This does however not work, since it still returns to many results which cannot be hold in memory. I am aware of this `cutoff`-argument.


> I'm afraid that's not easy to do; the current implementation is essentially an (optionally depth-limited) DFS so the order in which you get the results depends on the order of the DFS traversal.

IMO it would be possible by using a BFS-like approach, at least for sorting them by length. But the implementation should not be changed, since the DFS traversal is much more efficient in regards of memory usage. This was only a thought.

---

I did some benchmarking, since i need this to be as fast as possible. I found out that by converting the graphs to `networkx` and then using the `networkx`  method: `networkx.algorithms.simple_paths.all_simple_paths` is 1.2x faster then the example above provided by me. This benchmark does include the converting step. However, the `igraph` implementation is still roughly 80x faster...

I could also provide some graphs or other examples if needed.

**Comment by iosonofabio** [comment]
Hi @Luxxii 

We're hoping to modernize the Python interface over the next year or so - if funding becomes available - and this kind of questions is useful to know what to aim for, thanks for that.

In your specific case, my advice would be:

- You mention you need it to be "as fast as possible". Alright, then code it in C, of course.
- If you can't do that because of time constraints, then "cutoff" is designed exactly for your purpose, cutting too long paths.

You say it's still too many paths: then it all depends on what you want to do with the paths downstream. If you want to store them, well just rent a computer with more RAM. If you want to process them in a map-reduce paradign (e.g. counting paths, classifying them into distinct categories, etc.) then it'd be useful to know what you are trying to do specifically, so we could look into where a callback could be injected to solve this kind of situation.

**Comment by Luxxii** [comment]
Hi @iosonofabio

Yes, C would be an option for this, but i would like to remain in Python for this use-case. Maybe the Python interface of igraph can be called via Numba. This could be faster than my current approach. However, i never tried this and am not sure if Numba recoginzes igraph.

Yes, the `cutoff` is designed for paths, which are not longer than `x`. I am NOT constrained by time, since i currently use a slower approach which terminates in a reasonable time.

---
Here is one concrete example, which `cutoff` "currently cannot solve": 

Let G be a graph (directed, acyclic)  having multiple paths from a dedicated `s`- and `e`-node. Very few of those edges are labled with `True`, all the others with `False`.  

What i would like to retrieve is all paths from G, which have less than `x` many edges marked with `True`.  Lets say that there are `k` many paths (very large, e.g. `10 000 000 000`), but only `k_true` many paths with up to `x` many edges labelled with `True` (e.g. `10 000`). 

Executing `get_all_simple_paths` with setting the `cutoff` to the longest possible path in G "could" give us all `k` paths, where we then would filter those paths to only the interesting `k_true` paths.  "Could", since this depends on how much RAM is available on a computer.

(NOTE: This is not what i am currently doing! I utilize the `cutoff`-parameter appropiately and map the above problem to the path-length!)

To solve this problem: A "customized exploration of the graph" (where we decide whether child nodes are worth exploring)  would be great, so that in Python (or other interfaces) such "complex" conditions can be implemented individually. 

However, this is not what i want from this issue, BUT this would really be a nice-to-have!

--- 
Specifically in this Issue: I was asking for an generator approach (or a callback as mentioned by @ntamas ) to reduce the memory usage and to process the resulting paths "on the fly".  You mentioned: 
>  If you want to process them in a map-reduce paradigm (e.g. counting paths, classifying them into distinct categories, etc.)

I already do such a "counting of paths", which is the reason why i already know how much storage is needed for the database. I cannot buy more RAM (8 TB of RAM or more is quiet expensive). The generator/callback approach would use only a few MB of RAM and e.g. could fill databases which have tens of TB available for storage.

**Comment by szhorvat** [comment]
another effective request for callbacks: https://stackoverflow.com/q/66995867/695132

C core function should also return vector_ptr instead of flat list with -1 separators

**Comment by iosonofabio** [comment]
Thanks for the explanation.

You seem a little confused as of how numba, Python, CPython, and igraph are all working.

I think the take-home message for us is that having a callback attached to a map-reduce (custom counting) operation would be useful across languages (that applies also to @szhorvat 's last link).

In practice though, if I were you I would just implement the thing in C rather than buying 8TB of RAM. You are trying to have huge graphs, very high speed, a custom filter function, and do it from the comfort of your Python living room: this sounds niche enough to me to warrant a few hundred lines of code.

**Comment by iosonofabio** [comment]
Agree @szhorvat, ideally we would use a pointer to paths (vectors) instead of the -1 sep trick
