### ISSUE TITLE
Test failure with Python 3.9

### ISSUE THREAD

**Issue by dotlambda** [igraph/python-igraph#379]
**Describe the bug**
```
======================================================================
ERROR: testHubScore (tests.test_atlas.GraphAtlasTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/test_atlas.py", line 105, in testHubScore
    sc = g.hub_score()
igraph._igraph.InternalError: Error at src/linalg/arpack.c:1006: ARPACK error. -- No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV

----------------------------------------------------------------------
```

**To reproduce**
```
nix build -f http://github.com/NixOS/nixpkgs/archive/4b2848d9a63319da1efba7734718f30c3eed82aa.tar.gz python39.pkgs.python-igraph
```

**Version information**
igraph: 0.9.1
python-igraph: 0.9.1

**Comment by ntamas** [comment]
Is this deterministic? We have occasionally seen ARPACK failures with certain centrality scores (hub/authority scores are the most typical) that point to convergence problems in ARPACK itself, but these appear rarely and also depend heavily on whether you are using an external or a vendored ARPACK library.

**Comment by dotlambda** [comment]
It is not, indeed.

**Comment by szhorvat** [comment]
@ntamas Maybe you can set a random seed?

Most ARPACK-using functions set a starting vector which includes a tiny random perturbation. It is not unusual for ARPACK to fail, depending on the starting vector. With PageRank, I've seen failure rates between 0.01% 0.1% with the vendored ARPACK and lower still with ARPACK-NG 3.8.

**Comment by dotlambda** [comment]
It occurred a second time right now, which makes two out of four times building it on Python 3.9 for me.

**Comment by szhorvat** [comment]
What ARPACK and BLAS/LAPACK versions/implementations are you using?

**Comment by dotlambda** [comment]
ARPACK is https://github.com/opencollab/arpack-ng/
BLAS is OpenBLAS

**Comment by szhorvat** [comment]
I can't seem to reproduce this on macOS 10.14 x86_64, when using ARPACK-NG 3.8.0 and OpenBLAS 3.14 from MacPorts. I ran it maybe 20 times or so.

However, I notice that when compiling python-igraph with the vendored C/igraph, there is an inconsistency with linking. `setup.py` takes the libraries to link to from the pkg-config file. Right now, that is always `-lblas -llapack`. On my system, these always end up linking to Apple's BLAS/LAPACK, regardless of the fact that the C core was built with OpenBLAS. So python-igraph seems to end up linking to Apple's BLAS even if we get CMake to find OpenBLAS instead when building the C core. This probably affects Homebrew @ntamas. On the upside, on macOS, I am told there is no conflict if we end up in a situation where we link to ARPACK which links to BLAS-implementation-1 while we link to BLAS-implementation-2. This is because symbols names are tied to the library from which they should come from. However, this might not the case on Linux ...

This goes way beyond my knowledge though.

**Comment by szhorvat** [comment]
In order to coerce it to actually link to OpenBLAS on my system, I needed to (1) change that `-lblas -llapack` to `-lopenblas` (2) get rid of Anaconda's OpenBLAS, as it kept picking up that one instead of the one from MacPorts.

**Comment by ntamas** [comment]
> python-igraph seems to end up linking to Apple's BLAS even if we get CMake to find OpenBLAS instead when building the C core. This probably affects Homebrew @ntamas. 

Luckily it's not the case; the C core links properly to OpenBLAS:

```
$ otool -L /usr/local/Cellar/igraph/0.9.1/lib/libigraph.0.dylib
/usr/local/Cellar/igraph/0.9.1/lib/libigraph.0.dylib:
	/usr/local/opt/igraph/lib/libigraph.0.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/local/opt/arpack/libexec/lib/libarpack.2.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/local/opt/openblas/lib/libopenblas.0.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/suite-sparse/lib/libcxsparse.3.dylib (compatibility version 3.0.0, current version 3.2.0)
	/usr/local/opt/glpk/lib/libglpk.40.dylib (compatibility version 44.0.0, current version 44.1.0)
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 15.0.0, current version 15.1.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
```

However, the macOS wheel does not use igraph from Homebrew so it probably links to Apple BLAS/LAPACK.
