### ISSUE TITLE
Can't plot graph in Google Colab

### ISSUE THREAD

**Issue by gus0k** [igraph/python-igraph#384]
**Describe the bug**

I loaded the graph from a GraphML file and when I try to plot it, I get the following error:

```python
ValueError: palette index used when no palette was given
```

Plotting was working with other graphs.

**To reproduce**

[Link to Minimal Colab](https://colab.research.google.com/drive/1Cfaj98xcKxpsqKnvy0fVSXFd4PG_vFpj?usp=sharing)

**Version information**

```sh
Successfully installed python-igraph-0.9.1 texttable-1.6.3
```

**Comment by ntamas** [comment]
This is unrelated to Colab, it also happens with plain `python-igraph` in the command line.

The reason why you are getting this message is because your graph contains a `color` numeric vertex attribute. igraph uses this vertex attribute to set the colors of vertices on the plot; however, since the attribute is numeric, igraph would also need a _palette_ to convert numbers to colors. There are three workarounds:

* You can delete or rename the `color` vertex attribute altogether with `g_karate.vs["Color"] = g_karate.vs["color"]` followed by `del g_karate.vs["color"]`
* You can ask igraph to set a fixed vertex color for all vertices in the `plot()` call: `plot(g_karate, vertex_color="red")`
* You can provide a palette to the `plot()` call: `plot(g_karate, palette=ig.ClusterColoringPalette(32))` (where 32 is an arbitrarily large number that is larger than the number of clusters you have)
