### ISSUE TITLE
Plottig broken in jupyter lab and chrome

### ISSUE THREAD

**Issue by jvail** [igraph/python-igraph#388]
I found a very bizarre behavior with plotting in jupyter lab (3.0.14), igraph (0.9.1) and google chrome (90.0.4430.72) both on linux and windows: Whenever I plot a graph it tries to render the complete jupyter lab UI, it seems. Does not happen in firefox or classical notebooks.  

I am not entirely sure if it is an igraph (maybe cairo) issue. But all other libraries/widgets I use in the notebooks work just fine. Here is a sceenshot:

![image](https://user-images.githubusercontent.com/6503378/115340377-983aa780-a1b7-11eb-978a-b34891c3504f.png)

**Comment by iosonofabio** [comment]
Can confirm on Chromium + `python-igraph` 0.9.1, not a problem on Firefox as described.

I'm a little confused because I never use jupyterlab, but I'll take a look at the DOM and see if there's anything suspicious going on.

**Comment by ntamas** [comment]
The `iframe` thing can be turned off by editing `igraph/drawing/__init__.py` a bit. In the `_repr_svg_()` method of the `Plot` class, the return value looks like this:

```
return result, {"isolated": True}
```

Removing `{"isolated": True}` will turn off the `iframe` and the generated SVG will be inlined. I believe this is what @iosonofabio sees for 2-3 seconds. The problem with inlining becomes apparent when you try to plot multiple graphs within the same Jupyter notebook and you use node labels; see https://github.com/igraph/python-igraph/issues/222 for more details. The iframe was introduced exactly because of this problem.

So, if the problem is with the iframe, one workaround that comes to my mind is to take the generated SVG (this comes out of Cairo so we have no control over its contents), parse it as XML, and replace the XML IDs in the SVG with unique identifiers that we generate from a global unique ID generator. The issue outlined in #222 happens because Cairo re-uses SVG IDs (as it does not know that subsequent plots will be used in the same DOM context).

**Comment by agoose77** [comment]
Here's a reproducer (cross-posted to JupyterLab issues) https://mybinder.org/v2/gist/agoose77/9bce8bcbc3ca393d216c9afce3efdcc4/HEAD?urlpath=lab/tree/reproducer.ipynb

**Comment by jvail** [comment]
It seems, according to @agoose77,  it is not an issue in igraph. I''ll close and thank you for the super quick response.

**Comment by agoose77** [comment]
For posterity, [here is the JupyterLab issue](https://github.com/jupyterlab/jupyterlab/issues/10121).

**Comment by ntamas** [comment]
Also for posterity, [here is the fix in JupyterLab](https://github.com/jupyterlab/jupyterlab/pull/10185).
