### ISSUE TITLE
Self-loops are sometimes cut off with the matplotlib backend

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#393]
**Describe the bug**
Self-loops are sometimes partially outside of the frame with the matplotlib backend.

It is possible that this is due to my lack of knowledge about matplotlib, and that I just didn't set it to show everything.

**To reproduce**
```
import matplotlib.pyplot as plt

g = ig.Graph.Formula('0-1-2-3-4-5-0,1-1',simplify=False)

fig, ax = plt.subplots()
ax.set_aspect('equal', 'box')
ig.plot(
    g,
    target=ax,
    vertex_size=8, edge_alpha=0.3,
)

plt.show()
```

![image](https://user-images.githubusercontent.com/1212871/119013552-632c9b00-b997-11eb-812e-6917f22a74ed.png)

**Version information**
0.9.1.

**Comment by ntamas** [comment]
I leave this up to @iosonofabio to respond to as he is the most familiar with the Matplotlib backend, but I think that this problem is probably harder to fix as Matplotlib decides the bounding box based on the area spanned by the "data points", which are the vertices themselves. I don't think that it takes the extents of the decorations (edges, labels etc) into account.

**Comment by iosonofabio** [comment]
I tried this for a little bit and decided it's not worth bothering unless we want to improve the whole mpl support a lot. ATM it's basically a single, large stopgap function.

For the current user, `ax.ser_ylim(top=1)` is easy enough

**Comment by ntamas** [comment]
One thing that bothers me about the MPL backend is that Matplotlib is a heavyweight beast. On the other hand, I know that everyone has terabytes of storage available at his fingertips and Matplotlib is way easier to install nowadays than before, especially in comparison to Cairo, which is a niche thing in the Windows world. So, taking everything into account, I am in favour of committing ourselves to using Matplotlib as the primary plotting backend _if_ it is commonly deployed in notebook environments in a way that users don't have to install it manually.

I just checked Googe Colab and `import matplotlib` seems to work in an empty notebook, so that's a plus. Does anyone know whether Matplotlib is a standard part of other notebook-like environments that we would like to support, or shall I put aside some time to researching it?
