### ISSUE TITLE
"Unknown fields" in documentation

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#405]
**Describe the bug**

"Unknown field" appears in multiple places in the documentation.

Examples:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/1212871/119991159-74922a80-bfc9-11eb-8dba-15f7b8152b65.png">

https://igraph.org/python/doc/api/igraph._igraph.GraphBase.html#community_multilevel

**Version information**
0.9.1

**Comment by ntamas** [comment]
This is due to PyDoctor not supporting custom fields from Epytext (in particular, the `@newfield` directive). We either need to clean these up in the documentation or send a patch to PyDoctor to start supporting custom fields from Epytext. I'm leaning towards the former as it is easier, although the formatting of references would be nicer with the latter.

**Comment by ntamas** [comment]
I've started cleaning this up in `develop`.

**Comment by ntamas** [comment]
Docs cleaned up.

**Comment by iosonofabio** [comment]
Awesome job
