### ISSUE TITLE
AttributeError: type object 'Graph' has no attribute 'layout_grid_fruchterman_reingold'

### ISSUE THREAD

**Issue by luneice** [igraph/python-igraph#417]
Make sure that these boxes are checked before submitting your issue -- thank you!
Enviroment:
```
Ubuntu 18.04 LTS
Python 3.8
python-igraph 0.9.6
```
When running this code, it got `AttributeError: type object 'Graph' has no attribute 'layout_grid_fruchterman_reingold'` error:
```
...

visual_style["bbox"] = (3000, 3000)
visual_style["layout"] = g.layout("grid_fr")
visual_style["margin"] = 50
visual_style["edge_width"] = 0.1
visual_style["edge_curved"] = False
plot(g, **visual_style)
```
- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
`Graph.layout_grid_fruchterman_reingold()` was deprecated in `python-igraph 0.8` and was removed recently. The alternative is to use `g.layout("fr", grid=True)` instead. Unfortunately I was a bit careless when removing the method as I falied to removed the string-based aliases. This will be fixed in the next patch release.
