### ISSUE TITLE
Node Transparency

### ISSUE THREAD

**Issue by yjgeno** [igraph/python-igraph#430]
**What is the feature or improvement you would like to see?**
Hi thanks for the package! I was wondering if there is any argument that adjusts the opacity/transparency of vertices?

**References**
something in r:
https://stackoverflow.com/questions/30376904/changing-node-vertice-opacity-in-igraph-in-r

**Comment by iosonofabio** [comment]
Thanks for asking. we are working on a big PR that will enable that in matplotlib and perhaps plotly.

Should be ready in a week or two.

For now I'd think perhaps just using the `alpha=0.5` keywork argument to `ig.plot` might actually work.

**Comment by yjgeno** [comment]
@iosonofabio thanks for your response but set alpha in ig.plot will make the whole surface opaque. What I wanted was on nodes only... looking forward to your big improvement!

**Comment by iosonofabio** [comment]
are you using the Cairo or matplotlib backend?

**Comment by ntamas** [comment]
@iosonofabio Which part of the drawing machinery handles the `alpha` argument here? Is it Matplotlib or do we handle it ourselves in the Matplotlib backend? I'm asking because I thikn the `alpha` argument is not handled by the Cairo backend. In Cairo, you can make nodes semi-transparent by passing the color in RGBA notation like this:

```python
from igraph import Graph, plot

g = Graph.GRG(100, 0.2)
plot(g, vertex_color="#ff000080")
```

The downside of this is that the Cairo backend actually draws the edges from the centers of the nodes so even though the nodes will be semi-transparent, you will see the edges behind the nodes.

**Comment by iosonofabio** [comment]
The new matplotlib support is in the `develop` branch now. @yjgeno if you can test it you'd help us close this, otherwise wait until it hits pypi and then you can test it.

**Comment by vtraag** [comment]
Can this be closed, seeing that it is implemented in both `cairo` and `matplotlib`? Perhaps because the node transparency still shows the edges behind it, you'd like to keep it open @ntamas?

**Comment by ntamas** [comment]
We can close this; the fact that the edges are shown below the now-transparent node is another issue.
