### ISSUE TITLE
Add buffering to `Graph.DictList`

### ISSUE THREAD

**Issue by iosonofabio** [igraph/python-igraph#436]
@vtraag raised the issue in #434: Our `Graph.DictList` has a boolean `iterable` keyword arg that is designed for large graphs, but it most likely results in a significant runtime slowdown.

Changing the API and implementation to allow for any positive integer that acts as a buffer size would be a good compromise:

```python
g = Graph.DictList(..., iterative=1000)
```
should call `add_edges` every 1000 edges (and once more at the end).

Keeping this separate from that PR because it requires a little care to not lose vertex/edge attributes along the way.

**Comment by ntamas** [comment]
If we decide to do this, we should probably add a `batch_size` keyword argument as this is more descriptive. There are two ways I guess:

* We keep `iterative` as is, and add `batch_size` with a default value (say, 1000). When `iterative` is `False`, `batch_size` is ignored; it is considered only when `iterative` is truthy.
* We add `batch_size` with a default value of `None` and deprecate `iterative` such that `iterative=False` becomes `batch_size=None` and `iterative=True` becomes `batch_size=1` (or some more reasonable default value; 1 is probably the least efficient choice and it was chosen only because of its simplicity).

**Comment by iosonofabio** [comment]
Totally agree, would prefer option 2, hierarchies between function args can get a little confusing
