### ISSUE TITLE
Undocumented variables and No summery methods

### ISSUE THREAD

**Issue by Isaac-Lee** [igraph/python-igraph#463]
Hello :)

I was exploring the [python-igraph API reference](https://igraph.org/python/api/latest/classIndex.html) and found that the ㅡmost of instance variable was undocumented.
Not only that, there seems to be a part where Summery for the methods are too long, so it is displayed as "No summery".

Seeing that most of the undocumented instance variables use the values ​​of the constructor's parameters as they are, writing the  docstring for those variables seemed to be a simple iterative work.

I have **two questions** here.
1. Is there any reason the variable is not documented?
2. If they need to be documented can I work on documenting with a few colleagues who are interested in this project.

**Comment by iosonofabio** [comment]
Hello and thanks for the message.

I'm not sure what you mean. Do you mean we are not documenting `__init__` properly?

Please provide example

**Comment by Isaac-Lee** [comment]
Oh sorry my bad.

Yes the Instance Variables in `__init__` is not documented

For example, at the page about class [igraph.drawing.baseclasses.AbstractXMLRPCDrawer](https://igraph.org/python/api/latest/igraph.drawing.baseclasses.AbstractXMLRPCDrawer.html), there is no documentation about Instance Variable `server` and `service`. Also there is a docstring for `_resolve_hostname` but there is no summery for the method. I assume the docstring is to long so the pydoctor can't make summery.

**Comment by iosonofabio** [comment]
Thank you for the example. That's an abstract class, and the constructor is actually documented. So not a fantastic place to make your first contribution.

If you and your colleagues would like to contribute to python-igraph, I'd recommend starting by writing a few tutorials, asking the lines of #460 .

**Comment by Isaac-Lee** [comment]
Thank you very much for the comment and recommendation!
Will read some more and give it a try :)

**Comment by ntamas** [comment]
Actually, most of the cases where a private method or variable (starting with `_`) appears in the documentation and is shown as "undocumented" is an issue with the site CSS. These methods and variables are marked in the HTML markup with the CSS class `private`, but since we are customizing the PyDoctor CSS, they do not become hidden automatically by default. I'll fix the CSS and most of these should then go away.

**Comment by ntamas** [comment]
Aaargh, it's worse than that. Actually, we considered this before and it turns out that we cannot simply respect PyDoctor's `.private` CSS classes because it considers the entire `igraph._igraph` module as private due to the underscore so we wouldn't be able to show `igraph._igraph.GraphBase`. I'll try to come up with a more restrictive set of rules.

**Comment by ntamas** [comment]
Okay, should be fixed by now.
