### ISSUE TITLE
Tutorial is incorrect about colour specifications

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#465]
The tutorial claims that colours can be specified as 3-tuples of integers from 0 to 255. This is wrong. It should be tuples of reals from 0 to 1.

https://igraph.org/python/tutorial/0.9.8/tutorial.html#specifying-colors-in-plots

**Comment by ntamas** [comment]
Actually, it is even worse than that; all three options below work correctly:

```
plot(g, vertex_color=[(1.0, 0.5, 0)] * g.vcount())  # list-of-tuples in range 0-1
plot(g, vertex_color=[[1.0, 0.5, 0]] * g.vcount())  # list-of-lists in range 0-1
plot(g, vertex_color=["255, 127, 0"] * g.vcount())  # list-of-strings in range 0-255
plot(g, vertex_color=["#ff7f00"] * g.vcount())  # list-of-strings, CSS notation
plot(g, vertex_color=["rgb(255, 127, 0)"] * g.vcount())  # list-of-strings, CSS notation v2
```

I think the odd one out here is the `"255, 127, 0"` version. Internally, we use RGB components in the range 0-1 (mostly because both Cairo and Matplotlib uses them as far as I know). CSS notation is familiar to many people, though, and we can't argue with the CSS standard so we use 0-255 there. The fact that `"255, 127, 0"` works is actually new to me; I think this is somehow a side-effect of the CSS notation parsing where we strip the `rgb(` prefix and the `)` suffix first and then parse stuff by splitting the string around commas.

The docs are definitely wrong in the sense that it gives the impression that RGB tuples or lists use the range 0-1 so I'll fix that.

**Comment by ntamas** [comment]
Another issue to sort out: the machinery that generates the HTML documentation pages on the homepage does not support pointing the docs of a specific version at a commit that does _not_ belong to the version tag so we'll need to wait with fixing this on the homepage until the next patch release comes out, or I need to mess with the HTML manually.
