### ISSUE TITLE
Iterating through Python VertexClustering

### ISSUE THREAD

**Issue by ayushidalmia** [igraph/python-igraph#49]
I am trying to do community detection on a graph. When I try to iterate through the vertexCluster obtained from my graph, I get different membership as compared to printing the vertexCluster directly. Where am I going wrong in my understanding?

The following is the piece of code:
```python

from igraph import * 
g = Graph.Read_Ncol("network.txt", directed=False)
communityCluster = g.community_infomap()

print communityVertexClustering  \\Gives a different list when compared to the following lines
print communityVertexClustering[0]

```
```
Output:
[ 0] 740, 15, 991, 994, 996, 997, 998, 999, 1000, 48, 985, 59, 995, 132, 138,
     606, 182, 188, 982, 976, 936, 243, 932, 496, 255, 271, 278, 959, 589,
     329, 745, 414, 417, 420, 422, 434, 898, 983, 499, 933, 596, 620, 640,
     678, 693, 915, 759, 815, 829
[ 1] 275, 238, 953, 758, 76, 956, 969, 975, 986, 989, 992, 909, 96, 770, 103,
     937, 856, 162, 910, 960, 203, 767, 922, 206, 643, 858, 260, 551, 286,
     343, 426, 870, 435, 443, 725, 534, 482, 488, 517, 544, 623, 575, 581,
     708, 605, 655
....

78 99 100 101 102 103 104 105 106 255 256 295 296 545 558 570 637 650 651 699 722 729 739 740 744 764 772 821 829 830 881 897 902 903 904 915 949 953 954 962 986 989 992 993 995 996 997 998 999

```
If you notice the set of nodes in the first line of communityVertexClustering is different from the output of the second print statement. 
 
I have attached the network.txt file.

[network.txt](https://github.com/igraph/python-igraph/files/40832/network.txt)

**Comment by ntamas** [comment]
No mistake here; `communityVertexClustering[0]` returns the numeric vertex IDs of the nodes while `print communityVertexClustering` resolves the numeric vertex IDs to the names of the vertices (see `g.vs["name"]`). When reading from the NCOL format, the names of the vertices do not necessarily coincide with the IDs of the vertices since the IDs must always be in the range [0; |V|-1]. Since the NCOL format does not guarantee that (it can even have symbolic vertex names), igraph makes up the numeric vertex IDs on its own and stores the original IDs from the NCOL file in the `name` vertex attribute.

If your input file contains vertex IDs strictly in the range [0; |V|-1], use `Graph.Read_Edgelist` to keep the original numeric IDs (then you won't have a `name` vertex attribute at all).

**Comment by ayushidalmia** [comment]
Thanks. Also, when will we have a good documentation for this awesome library?

**Comment by ntamas** [comment]
Cannot tell - I'm very short on spare time nowadays :(

**Comment by ayushidalmia** [comment]
:(
