### ISSUE TITLE
Running Graph.shortest_ paths() occurr the problem of 'Process finished with exit code - 1073741819 (0xc0000005)'.

### ISSUE THREAD

**Issue by liyunlong666** [igraph/python-igraph#537]
**Describe the bug**
I'm running a graph (vertices:46567, edges:55697) with weights Graph.shortest_ paths(), it will automatically terminate the program and prompt 'process finished with exit code - 1073741819 (0xc00000005)'. But running this function on a slightly simpler network (vertices:18081, edges:17131) with same weights is successful. 

I tried several ways to solve the problem, but to no avail. Thank you very much for helping me answer this question.

**To reproduce**
length = G.shortest_paths(weights='length')

igraph.Edge: (<igraph.Graph object at 0x000001A0B1E46D68>, 0, {'length': 0.938476026058197, 'GB': 11.0})"

**Version information**
0.9.10

**Comment by szhorvat** [comment]
This operation would allocate a matrix with more than 46567 * 46567 > 2^31 - 1 elements, which is not supported in 0.9, especially on Windows (might work on Linux/macOS if you're lucky). This is already fixed in the development version, which will eventually become 0.10.

You can try the development version now, but you need to compile it yourself. See the instructions in the readme: https://github.com/igraph/python-igraph/

**Comment by liyunlong666** [comment]
Thank you very much. I'm looking forward to the new version. When will the new version be released?

**Comment by szhorvat** [comment]
> When will the new version be released?

Unfortunately that is not clear yet. igraph is undergoing significant refactoring, which will take some time.

**Comment by liyunlong666** [comment]
OK, we all look forward to a better iGraph. Thank you again for your contribution. I hope your life and work are going well.
