### ISSUE TITLE
wrong operation graph union

### ISSUE THREAD

**Issue by alexfdo** [igraph/python-igraph#542]
```
list_names = [
    ['вод', 'природн', 'питьев', 'газирова', 'свят', 'источник', '0', '33', 'упаковк', '12', 'штук'],
    ['вод', 'питев', 'газирова', 'свят', 'источник', 'активн', 'минерал', 'газирова', 'обогащен', 'магн', '12', 'штук', '500', 'мл'],
    ['вод', 'минеральн', 'боржом', 'газирова', '0', '33', 'л', 'жестян', 'банк', '12', 'штук', 'упаковк']
]

def create_graph_for_name(names_list):
    g = ig.Graph.Full(len(names_list))
    g.vs["name"] = names_list
    return g

def create_graph_context(list_names):
    list_g = []
    for name in list_names:
        list_g.append(create_graph_for_name(name))
    gc = ig.operators.union(graphs=list_g, byname=True)  
    return gc

graph_context = create_graph_context(list_names)
print(graph_context.summary())
graph_context.vs["label"] = graph_context.vs["name"]
ig.plot(graph_context, bbox=(600, 430), vertex_size=12, vertex_label_size=12, vertex_label_color='blue', margin=40)

```
This operation creates an extra isolated vertex, as shown in the screenshot below.
I had to make a crutch in the form of the following code
```
""" deleting an isolated vertex """
n_last = len(list(gc.vs()["name"]))-1
if not gc.degree(n_last):
    gc.delete_vertices(n_last)

```
![Выделение_999(272)](https://user-images.githubusercontent.com/29231622/170271383-4f18f37d-a066-4a88-aa3d-4cec3fd257f7.png)

**Comment by szhorvat** [comment]
@iosonofabio Can you have a look? This was your code as far as I remember.

**Comment by szhorvat** [comment]
@alexfdo Can you please produce a _minimal_ example where vertex names use only ASCII characters?

**Comment by szhorvat** [comment]
You are using non-unique vertex names for the second graph. `'газирова'` appears twice. This is a good example of why it's important to always create a minimal example before submitting a bug report.

**Comment by alexfdo** [comment]
> You are using non-unique vertex names for the second graph. `'газирова'` appears twice. This is a good example of why it's important to always create a minimal example before submitting a bug report.

IMHO you rushed to close my appeal. This will not fix the error.
Look closely at the following screenshot

![Выделение_999(273)](https://user-images.githubusercontent.com/29231622/170463272-150248d1-1fa0-4843-9d94-6252c6351cb3.png)

**Comment by alexfdo** [comment]
Or do I need to re-open the issue so you can take care of the error?

**Comment by szhorvat** [comment]
Please do not open new issues for the same topic. The conversation can be continued here.

The `name` attribute must contain unique values for each graph, otherwise vertices are not distinguishable. Ideally there would be a check that prevents setting the same name for two vertices, but this is not yet implemented.

I closed this issue because it is not a bug in igraph, but a problem with your code. You assigned the same name to two different vertices in the second graph, which caused the union operation to go awry.  If you fix this, the result of the union will be correct. If you have an example where this is not the case, please show it (ideally a minimal version).

The note you highlighted in the documentation says that vertices may appear in more than one graph. Vertex names within a single graph must still be unique.

**Comment by szhorvat** [comment]
I will look into improving the situation so that `union` and `intersection` would reject graphs with invalid `name` attributes even before a more general check on duplicate names is implemented.

**Comment by alexfdo** [comment]
Thanks a lot.
I saw my mistake. I checked the names between charts, but didn't notice any duplication within one. And now your first answer has become clear to me.
Excuse me for this fuss.
Sincerely, Alexander
