### ISSUE TITLE
Method graph.components doesn't show up in the documentation

### ISSUE THREAD

**Issue by adamoppenheimer** [igraph/python-igraph#549]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [✓] This issue is for the Python interface of igraph.
- [✓] This issue is a bug report or a feature request, not a support question.

I have been using the method `graph.components` so that the terminology is similar to `graph.biconnected_components`, but I couldn't find it in the documentation.

Eventually I looked in the source code and realized that the method `graph.components` is just a copy of the method `graph.clusters`, but I believe this is overlooked by the documentation generator you are using, so `graph.components` doesn't show up at all.

Thank you!

**Comment by ntamas** [comment]
Thanks for the feedback. Yes, this is a bit quirky; for historical reasons, the primary instance of this method is called `clusters` because it is `igraph_clusters()` in the underlying C library (but note that the C library will deprecate this name from version 0.10 and rename it to `igraph_connected_components()`, and the Python interface will eventually follow suit). PyDoctor does not include aliases by default in the generated API documentation. I wonder what we could do to make the function more discoverable -- would it helped if we listed it explicitly as an alias in the docstring of `Graph.cluster()` with a sentence like this:

> This function is also aliased as `Graph.components()`.

This would probably help with discoverability if someone is searching through the docs with Ctrl-F.

**Comment by adamoppenheimer** [comment]
I think your idea would be a helpful change.

The issue I was having was that it doesn't show up in the documentation at all, so this would resolve that - thank you!

I'm not sure if I should leave this open until you update the documentation, so I won't close it for now.

**Comment by ntamas** [comment]
I have updated the docs in ce527fd and also deprecated `.clusters()` in favour of `.components()`.
