### ISSUE TITLE
Update modularity() to support resolution parameter

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#552]
**What is the feature or improvement you would like to see?**

Update `modularity()` to support resolution parameter

**Use cases for the feature**

 - Feature parity with C core
 - Working with Leiden community detection
 - `resolution=0` allows counting intra-community edges

**Comment by ntamas** [comment]
It's already done in the `develop` branch, and since igraph 0.10.0 is close to a release now, I'd rather wait until igraph 0.10.0 is out, and then merge the `develop` branch here into `master` and make a `python-igraph` release as well (even if not all the new stuff in igraph 0.10.0 will have a Python interface by then).
