### ISSUE TITLE
RTD doc pages have version encoded in their URL

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#612]
The docs on RTD have the version encoded in their URL. If I go to https://igraph.readthedocs.io/, it redirects to https://igraph.readthedocs.io/en/0.10.2/ This is not ideal as it will lead to many links around the internet pointing to outdated (and often incomplete) documentation. See the situation with CMake.

Some other projects use a version-agnostic URL by default, such as "stable" or "latest".  Do we want to do the same?

**Comment by ntamas** [comment]
Okay, I thought I've configured this properly, but it looks like I didn't (or I configured something else :)). But I think it's okay now. Note that due to in-browser caches you might still get the old redirect if you browse to https://igraph.readthedocs.io/, but this is what I get from the command line:

```
❯ http https://igraph.readthedocs.io/
HTTP/1.1 302 Found
[...snip...]
Location: https://igraph.readthedocs.io/en/stable/
[...snip...]
```
