### ISSUE TITLE
induced_subgraph does not work in a subclass of ig.Graph

### ISSUE THREAD

**Issue by lnajman** [igraph/python-igraph#639]
**Describe the bug**
When creating a subclass of Graph, induced_subgraph returns an error.

**To reproduce**
The following is working:
```python
lnames = ['0', '1']
edgelist = [('0', '1')]
weights = [0, 1]
graph = ig.Graph(len(lnames),  vertex_attrs={'name': lnames, 'weight': weights})
graph.add_edges(edgelist)
graph.induced_subgraph(graph.vs.select(weight_ge=0))
```

The following is not
```python
class mygraph(ig.Graph):
  def __init__(self, lnames, edgelist, verticeWeights):
    super().__init__(len(lnames), vertex_attrs={'name': lnames, 'weight': verticeWeights})
    self.add_edges(edgelist)

  def lambdaSection(self, level):
    '''Returns the Hasse diagram of the subcomplex with weight >= level'''
    _v = self.vs.select(weight_ge=level)
    #_class = self.__class__
    #self.__class__ = ig.Graph
    g=self.induced_subgraph(_v)
    #self.__class__ = _class
    return g

graph = mygraph(lnames, edgelist, weights)
graph.lambdaSection(0)
```
It returns the error:
```python
TypeError: __init__() got an unexpected keyword argument '__ptr'
```

Uncommenting (removing the #) in the class solves the issue, but this is an ugly workaround.

**Version information**
igraph version: 0.10.4, with pip install igraph

**Comment by ntamas** [comment]
The `Graph` constructor has a hidden argument named `__ptr` that is used when the C core hands us an already-initialized `igraph_t` object (which is the case for `induced_subgraph()` and we need to wrap it in a `Graph` instance. In such cases, a hidden `__ptr` argument is used to pass the pointer to the `igraph_t` object to the constructor.

The solution is not to override the constructor signature unless necessary. In your case, it's not necessary as you can provide a convenience function as a class method instead of a constructor:

```
class mygraph(ig.Graph):
    @classmethod
    def from_names_edgelist_and_weights(cls, lnames, edgelist, verticeWeights):
        result = cls(len(names), vertex_attrs={'name': lnames, 'weight': verticeWeights})
        result.add_edges(edgelist)
        return result
```

But, if you really want to override the constructor, you can, but then you need to make sure that it can be invoked with a single `__ptr` keyword argument only. You can achieve this with a `**kwds` catch-all argument and reasonable defaults for your custom arguments. So, something like this:

```
def __init__(self, lnames=None, edgelist=None, vertex_weights=None, **kwds):
    if "__ptr" in kwds:
        super().__init__(**kwds)
    else:
        # you can do whatever you want here
        super().__init__(..., **kwds)
        self.add_edges(edgelist)
```

**Comment by ntamas** [comment]
I'm inclined to close this as this issue is not specific to igraph; if you have a class with a method or constructor with a specific call signature, and the class itself happens to use this call signature, and then you override the call signature in a subclass, things will break just like they broke here. Feel free to reopen if you disagree and have an alternate proposal for dealing with the `__ptr` argument.

Note that I also considered adding a class method to the `Graph` class like this:

```
@classmethod
def wrap_existing_igraph_t(cls, ptr):
    ...
```

but the body of this method would _still_ need to be able to construct an instance of the class _somehow_, and if you override the constructor, there is no guarantee that the new constructor is compatible with whatever the `wrap_existing_igraph_t` method would expect, so we would still have the same problem.
