### ISSUE TITLE
More precise control over vertex count in constructor

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#641]
Currently, the graph constructor determines the vertex count automatically: `Graph([(0,1), (1,2)])` uses 3 vertices. This is of course very convenient. But what if we want to specify the vertex count manually, and want guarantees that this is respected?  This still works, `Graph([(0,1), (1,2)], n=1)`, and results in 3 vertices.

The "strict" way to do this is a bit more verbose:

```
g = Graph(n=1)
g.add_edges([(0,1), (1,2)]) # errors as we only have one vertex
```

Proposal:

 - If `n` is not explicitly specified, it should be determined automatically, just as it is now.
 - If `n` is specified, it should be respected, and invalid IDs should be detected in the edge list.

What do you think @ntamas? This is of course only for the new ctypes-based interface. Yes, I know this is not consistent with what the C core does, but the question here is what is most useful/convenient for the Python interface, not C.

**Comment by szhorvat** [comment]
@ntamas, opinions?

**Comment by ntamas** [comment]
Closing this as I'm still of the opinion that such functionality belongs to the C core so it can be shared between higher-level interfaces. (This will become even more important with the new ctypes-based generated Python interface because we would not need to provide a custom implementation for the graph constructor with this added logic if the check is done in C).

Feel free to reopen if you disagree.
