### ISSUE TITLE
MemoryError in method distances

### ISSUE THREAD

**Issue by yizhihenpidehou** [igraph/python-igraph#650]
**Describe the bug**
MemoryError, Error at src/core/vector.c 475 Cannot reserve space for vector --out of memory.
I met this problem when I want to take the distances method and calculate the shortest path matrix from each node in the graph.

**To reproduce**
Steps or minimal example code to reproduce the problem.
I used roads dataset, which has 129165 nodes and 165435 edges. However, I got MemoryError in my server.
I have tried to track the %MEM in my server ,I found that the memory usage was upwards of 98%.  I have no idea why this problem occurs.
`
def run_time2(b):
    # ig_file = open("ig_res.txt",'w')
    node_num = len(b.vs)
    print("node_num:",node_num)
    res_list =[]
    start = time.perf_counter()
    # for i in range(0,165435):
    #     res = get_shortest_paths()
    res = b.distances(weights = b.es["weight"])
        # res_list.append(res)
    end = time.perf_counter()
    # ig_file.close()
    return end - start

b = ig.Graph()
b = ig.load(filename="roads/a.lgl")
print("ig:",run_time2(b))

`
If you are confident that the issue is not in the Python interface but in the
C core of igraph, please add it to the main [igraph repo](https://github.com/igraph/igraph)
instead.

If you are unsure, feel free to add your issue here - we will transfer it to
the main [igraph repo](https://github.com/igraph/igraph) if the root cause is
in the C core of igraph.

**Version information**
python-igraph 0.10.4

**Comment by yizhihenpidehou** [comment]
Thanks for your rapid answer! But I have 189GB available memory on ubuntu.

**Comment by ntamas** [comment]
True, but the Python interface represents the result matrix as a list of lists, and in Python, each item in the list is going to be a Python _object_ so it will take up much more than 8 bytes. If you really want to calculate the shortest paths for a graph of this size in one iteration, you should probably use igraph from C directly because then you won't have to pay the overhead of Python objects.

An alternative is to calculate the shortest path matrix row by row. Then you only need a Python list of length 129165, and you can use a pre-allocated NumPy array that you copy the returned lists into.

**Comment by szhorvat** [comment]
As a practical solution, consider generating a few rows of the distance matrix at a time (i.e. set the `source` parameter to a subset of vertices at a time). Process that data, then discard it, and move on to the next few rows.

**Comment by yizhihenpidehou** [comment]
Thank you very much for your explanation and practical solutions, it is helpful and enlightening！
