### ISSUE TITLE
IGraph accepts large integers vertices, but overflows when adding edges to them

### ISSUE THREAD

**Issue by vitorbaptista** [igraph/python-igraph#664]
**Describe the bug**

I can create int vertices larger than the maximum edge vertex. For example, I can create the vertex `107099649093215534534`, but if I try to add its edges, I receive an OverflowError.

Quickly browsing through the igraph's C code, it seems the `add_vertex` accepts an unsigned int, while the `add_edge` uses signed ints. Not sure if it's related (my C is pretty rusty)

**To reproduce**

```python
import igraph as ig
graph = ig.Graph(directed=False)
graph.add_vertex(10709964909321)
graph.add_vertex(107099649093215534534)
graph.add_edges([(107099649093215534534, 10709964909321)])
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/home/vitor/.pyenv/versions/venv_musicdb/lib/python3.9/site-packages/igraph/basic.py", line 41, in _add_edges
#     res = GraphBase.add_edges(graph, es)
# OverflowError: int too big to convert
```

**Version information**

Version 0.10.4, installed via Pip. Python 3.9.13.

**Comment by szhorvat** [comment]
The line `graph.add_vertex(107099649093215534534)` adds a single vertex with the name `107099649093215534534`. This number is never passed to the C implementation. It's just a Python object that is used as the name of the vertex.

Vertex names should not be integers though, as in other contexts, integers will be interpreted as vertex IDs, not as names.  This is the case in `add_edges()`: `107099649093215534534` is now interpreted as a vertex ID, and is sent to the C core. Well, it _can't_ be sent to the C core because it cannot be represented as a 64-bit integer. Note that $\log_2 107099649093215534534 = 66.5$. Hence the error.

If you used smaller numbers, there would be an error about invalid vertex IDs. 

The main point is not to try to use integers as vertex names. Use strings. Integers will be interpreted as vertex IDs.

**Comment by szhorvat** [comment]
@ntamas How can we make this situation less confusing, and implement some protection against using vertex names that won't work in all contexts?

**Comment by ntamas** [comment]
I've added explicit protection against using integers for the `name` argument in `add_vertex()`. If we want more protection, the next obvious place to catch things like this is the attribute handler; we could explicitly disallow assigning integers to the `name` vertex attribute. But this means at least two things:

* an explicit runtime overhead of assigning to vertex attributes because we need to at least check whether the user is modifying the `name` attribute -- and if so, we need another `isinstance()` check to see whether the user is trying to assign an integer. (And actually, checking for integers might not be enough as NumPy has its own integer types and I'm not sure how those behave as vertex names).
* loading GraphML files with numeric names is not possible any more as the attempt to assign a number to the `name` vertex attribute would make the attribute handler throw an exception
