### ISSUE TITLE
get_shortest_path does not take parameter 'algorithm'

### ISSUE THREAD

**Issue by justuskilianwolff** [igraph/python-igraph#700]
**Describe the bug**
The docs of the current igraph version (0.10.6) say that it is possible to pass values ('auto', 'dijkstra', 'bellman_ford') to the algorithm parameter with the shortest path function. This doesn't work as I get the error "TypeError: 'algorithm' is an invalid keyword argument for this function". Since I need to compute the shortest path on a graph with some negative weights this is quite unfortunate.

The same holds for g.get_shortest_paths()

**To reproduce**
```
import igraph as ig
g = ig.Graph.GRG(100, 0.2)
g.get_shortest_path(v=0, to=10, algorithm='auto')
```

**Version information**
Version is igraph 0.10.6.

**Comment by justuskilianwolff** [comment]
To install I used `pip install igraph` and not `pip install python-igraph` (which seems to be the correct way regardind the pip page of python-igraph)

**Comment by szhorvat** [comment]
> The docs of the current igraph version (0.10.6) say that it is possible to pass values ('auto', 'dijkstra', 'bellman_ford') to the algorithm parameter with the shortest path function.

Where do you see this? Are you looking at the documentation for 0.10.6, or the documentation for the development version?

Docs for the stable version:

https://python.igraph.org/en/stable/api/igraph.GraphBase.html#get_shortest_paths

Docs for the dev version:

https://python.igraph.org/en/latest/api/igraph.GraphBase.html#get_shortest_paths

To install the dev version, you need to compile it from sources, https://github.com/igraph/python-igraph/#compiling-the-development-version

**Comment by justuskilianwolff** [comment]
Sorry my bad, I clicked on the function get_shortest_path() on this [page](https://python.igraph.org/en/latest/tutorials/shortest_path_visualisation.html) and assumed it would link to the latest stable release (in this case 0.10.6).

**Comment by justuskilianwolff** [comment]
Thank you, that's good to know (and I'll pay more attention to the domain next time). Nevertheless, I don't think that links from the gallery should link to the latest release (since the ordinary user will use a stable release).  Also, when I hover over the link it shows "in version 0.10.6." but redirect to the latest version, which I find slightly confusing:
![Screenshot 2023-08-08 at 14 41 47](https://github.com/igraph/python-igraph/assets/41119166/5f4038a4-09bf-4f82-a1a5-bb0d4e1e7dc1)

**Comment by ntamas** [comment]
> This is perhaps somewhat confusing, but I think it's fairly standard?

AFAIK it's standard, at least to the extent that Readthedocs [uses this naming scheme by default](https://docs.readthedocs.io/en/stable/versions.html):

> Read the Docs supports multiple versions of your repository. On initial import, we will create a `latest` version. This will point at the default branch defined in your VCS control. [...] If your project has any tags or branches with a name following [semantic versioning](https://semver.org/), we also create a `stable` version, tracking your most recent release.

As far as I know the links in the gallery should also point to the same version in which you are viewing the gallery itself. So, if you view the gallery from https://python.igraph.org/en/stable/tutorials/index.html, it should lead to other pages within `stable`; if you view it from https://python.igraph.org/en/0.10.6/tutorials/index.html, it should lead to to other pages within `0.10.6`. (The tooltip also reflects this).

If you find that this is not the case and links from the gallery lead out to other versions and not the one you picked, please send the link to the page having the issue here and we'll look into it.
