### ISSUE TITLE
Update platforms wheels are being created for

### ISSUE THREAD

**Issue by tim-stephenson** [igraph/python-igraph#742]
Currently there are the following wheel builds pushed to pypi (https://pypi.org/project/igraph/#files)
- Python versions:
  - cp38
  - cp39
  - pypy38
  - pypy39
  - pypy310

There should be builds for CPython 3.10, 3.11, 3.12.

The use case is that the most popular python version as of 2020 ([source](https://discuss.python.org/t/python-download-stats-for-march-2022/14908)) will have builds for it.

Also, the 32-bit builds on linux and windows can probably be dropped. I'd image those are an incredibly small about of the users.

**Comment by ntamas** [comment]
CPython 3.10, 3.11 and 3.12 wheels are not built because the CPython 3.9 wheels are also ABI3 wheels, thus they are compatible with any future Python version in the 3.x series. (You can install a `cp39-abi3` wheel on Python 3.10 without any problems).

As for the 32-bit builds, yes, they probably cater for a relatively small fraction of the user base, but right now the most time in the CI release build is taken up by building the `aarch64` wheels, which have to be built in QEMU, so these builds are incredibly slow. We can afford spending time on the 32-bit builds in parallel.

**Comment by ntamas** [comment]
Feel free to continue the discussion if you disagree and re-open the issue if you strongly disagree. I am open to suggestions, I just felt that the primary reason for this issue was the lack of dedicated CPython 3.10, 3.11 and 3.12 builds, and wanted to point out that these are not necessary.
