### ISSUE TITLE
publish manylinux package to pypi

### ISSUE THREAD

**Issue by abe-winter** [igraph/python-igraph#75]
Love igraph, hate installing a bunch of dependencies.

Is a manylinux wheel in the roadmap?

Happy to lend a hand on this -- project maintainer, assign this to me if that makes sense.

**Comment by ntamas** [comment]
To be honest, this is the first time that I've heard about manylinux wheels, but I'm glad that there's finally a proposal that should in theory allow us to compile and distribute binary packages on Linux.

I would be happy to make the Python interface of igraph manylinux-compatible, but since I don't use Linux myself any more, I definitely need a hand here. I think the easiest is if you fork the repo, add any necessary patches to make it work, and then send me a pull request.

FWIW, there are sample Dockerfiles in the `docker/` subdirectory, so you can probably use `docker/minimal/Dockerfile` as a starting point for building igraph in the Docker container provided by the manylinux project.

Let me know if you need any help with this.

**Comment by abe-winter** [comment]
Awesome. Thanks for the pointer to the dockerfiles. I'll make time for this sometime this week.

**Comment by abe-winter** [comment]
@ntamas this is ready for review. There are some notes in the PR on testing.

To upload wheels to pypi, the manylinux docs recommend using [twine](https://pypi.python.org/pypi/twine). If there's a CI task that uploads wheels automatically for this project, let me know and I'll edit.

**Comment by janschulz** [comment]
Acording to my knowledge, twine isn't easily used in CI services (e.g. https://github.com/pypa/twine/pull/165). That said, here is a script which includes such a step: https://github.com/janschulz/package-builder/blob/master/recipes/pypandoc/build.sh

You need to add $PYPI_USER and $PYPI_PASS secure variables to the CI environment...

**Comment by abe-winter** [comment]
@janschulz thanks for the pointer to your conda scripts. I assume the igraph team is on a slow release cycle and uploads to PYPI manually; I'll wait to hear from them before writing any CI.

**Comment by abe-winter** [comment]
@ntamas
- to generate the wheels, run `make build-wheel && make copy-wheel` in the repo root on a machine with docker installed. It will take ~ 30 minutes; the wheels will be in `docker/wheelhouse`.
- `make test-wheel` will run your test suite in various linuxes using the generated wheels

**Comment by ntamas** [comment]
Tried this and it seems to work great, thanks! I'll merge the pull request soon.

**Comment by ntamas** [comment]
The pull request (#76) is now merged both into `release-0.7` and `master`. Thanks for your work on this!

**Comment by abe-winter** [comment]
no problem, glad to help
