### ISSUE TITLE
`vertex_color` as tuple of RGB doesn't work

### ISSUE THREAD

**Issue by alex180500** [igraph/python-igraph#757]
Vertex color as a tuple of 3 RGB values from 0-1 (as stated in the tutorial: https://python.igraph.org/en/stable/tutorial.html#specifying-colors-in-plots) doesn't work.

**Code**
```py
import igraph as ig
graph = ig.Graph.Lattice((3, 3))
ig.plot(graph, layout="grid", vertex_color=(1.0, 0.0, 0.0))
```

**Actual behaviour**

<img src="https://github.com/igraph/python-igraph/assets/30732244/addd940d-11d1-48c5-b1e3-7bd6be0214ec" width="300">

**Expected behaviour**

<img src="https://github.com/igraph/python-igraph/assets/30732244/3e791d8b-c6b4-4b10-a884-6fe363655dc1" width="300">

**Versions**

python-igraph 0.11.3
python 3.12.1

**Comment by ntamas** [comment]
You need to do it like this:

```python
ig.plot(graph, layout="grid", vertex_color=[(1.0, 0.0, 0.0)] * graph.vcount())
```

The problem is that igraph is not using `(1.0, 0.0, 0.0)` as colors for all the vertices -- instead of that, it uses `1.0` for the first vertex, `0.0` for the second and third vertices, and then it starts recycling the tuple for the remaining vertices. This should probably be emphasized in the documentation, though.

**Comment by alex180500** [comment]
Perfect, yes the documentation should be more clear about it! Thanks a lot anyway

**Comment by alex180500** [comment]
Perfect, thanks a lot! yes the documentation should be more clear about it.
