### ISSUE TITLE
Building with an external igraph library on Windows

### ISSUE THREAD

**Issue by Kreijstal** [igraph/python-igraph#769]
quote from https://github.com/igraph/python-igraph/blob/19b5a45d0e987397256efa48fd447cec5e7315c9/README.md?plain=1#L161
Well pkg-config might not be supported, but pkgconf is https://packages.msys2.org/package/mingw-w64-x86_64-pkgconf which shims pkg-config... so this is not true. You can link to dll libraries lol in Windows

**Comment by szhorvat** [comment]
Why are you trying to link to an external igraph? What is your use case that requires this?

**Comment by Kreijstal** [comment]
> Why are you trying to link to an external igraph? What is your use case that requires this?

not having visual studio, installing igraph without admin access.
This is not only for me but for all msys2 users
This is my recipe:

`pacman -S $MINGW_PACKAGE_PREFIX-igraph`
and then 
`IGRAPH_USE_PKG_CONFIG=1 SETUPTOOLS_USE_DISTUTILS=stdlib pip install igraph`.

and then:
```
Successfully built igraph
Installing collected packages: texttable, igraph
Successfully installed igraph-0.11.4 texttable-1.7.0
```
Yay!   
I hope this helps someone else

**Comment by szhorvat** [comment]
On Windows, we recommend using either the official Python distribution and installing binary wheels from PyPI (a simple `pip install igraph`) or using Conda.

MSYS2 provides a Unix-like environment, so if you want to compile python-igraph from sources, you can do so. Linking to an external C/igraph is not necessary on MSYS2, but possible.

Since there is no actionable item in this issue, I'm closing it now. For support (including installation support) or general discussions, please use the forum at https://igraph.discourse.group/ We reserve the issue tracker for bug reports and feature requests.

**Comment by Kreijstal** [comment]
I meant msys2/mingw, not just msys2. The thing is yes, msys2 is unix compatible but the programs it makes through mingw do not need to have the unix compatibility, so you can just use it too bootstrap programs into windows. The bug/(actionable) is correcting the documentation, it is indeed possible to use external igraph in windows, and NOT "impossible". But that's your call to make. Thank you.

**Comment by ntamas** [comment]
I'll be happy to update the docs but I have zero experience with MSYS/MinGW and `pkgconf`, and I have no access to Windows machines either. Ideally someone should write up step-by-step instructions about how to do this on Windows and I'll be happy to include this in the docs. Without instructions, I can only claim that `pkgconf` shims `pkg-config` and it _might_ work.

@Kreijstal Can you send a PR with detailed instructions about how to get things working on Windows in MSYS/MinGW and `pkgconf`? If so, I'll merge that. If not, I'll just update the docs as outlined above and link to this issue.
