### ISSUE TITLE
Possible memory leak in	GraphBase.get_all_shortest_paths()

### ISSUE THREAD

**Issue by NealLong** [igraph/python-igraph#79]
My server has 64GB memory, and installed python-igraph-0.7.1.post6. The OS is Ubuntu 14.04 LTS, with python 2.7.6. My input graph is a s simplified graph with #nodes=54808,#edges=881672.  usually the computation consumes no more than 10GB memory, but sometimes it consumes  consumes all the 64GB memory, and then exits with a "Segmentation fault". 

I found that my problem is very similar to other users'  posts, 
http://comments.gmane.org/gmane.comp.science.graph.igraph.general/9834. 

Following the instructions for debugging in the above post, my relevant code is as follows (I skip the node with id<600,because the segmentation fault usually happens around after the first 680 runs):
```python  
self = Process()
MB=float(1024*1024)
print "#nodes=%d,#edges=%d,is_simply=%s"%(graph.vcount(),graph.ecount(),graph.is_simple())
for count,uid in enumerate(managerIdList):
    if count<680:
        continue
    otherUids = [x for x in managerIdList if x > uid]
    print "Compute the shortest paths to %d other users for betweeness from user-%d with %d neighbors "%(count,len(otherUids),len(graph.neighbors(uid))) 
    paths = graph.get_all_shortest_paths(v=uid, to=otherUids)
    del paths
    gc.collect()
    mem_info = self.memory_info()
    print "NodeId=%d, #reservedMem=%fMB, #virtualMem=%fMB"%(count, mem_info.rss/MB, mem_info.vms/MB)
```  
The printed information is as follows:
![igraph_output](https://cloud.githubusercontent.com/assets/4300763/15347205/df57a8a2-1cf1-11e6-9bcf-d22e834d336f.png)

and the consumed memory just before the segment fault is as follows:
![igraph](https://cloud.githubusercontent.com/assets/4300763/15347222/18535af2-1cf2-11e6-8ee9-5d88f4b6f818.png)

**Comment by ntamas** [comment]
Are you sure that the cause is not simply the fact that you have too many shortest paths from the source user to the target user(s)? Even with only a handful of vertices, it is not too complicated to construct a graph for which there are exponentially many paths from a given source vertex to some target vertices. For instance, consider a 10x10 grid graph. The distance from the upper left corner to the lower right corner has a path length of 18, but the _number_ of such paths is 48620.

If you are more or less sure that this is not the case, please upload your graph somewhere and send me a link so I can take a closer look at it.

**Comment by NealLong** [comment]
Yes, that's the problem. I just realized it, thanks a lot!
