### ISSUE TITLE
Test failure on 0.11.8

### ISSUE THREAD

**Issue by limburgher** [igraph/python-igraph#805]
**Describe the bug**
Building 0.11.8 with igraph 0.10.15:
=================================== FAILURES ===================================
_________________________ GraphTestRunner.test_labels __________________________

args = (<tests.drawing.matplotlib.test_graph.GraphTestRunner testMethod=test_labels>,)
kwds = {}

    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
E           matplotlib.testing.exceptions.ImageComparisonFailure: images not close (RMS 3.652):
E           	result_images/test_graph/graph_labels.png
E           	result_images/test_graph/graph_labels-expected.png
E           	result_images/test_graph/graph_labels-failed-diff.png

/usr/lib64/python3.13/contextlib.py:85: ImageComparisonFailure
=========================== short test summary info ============================
FAILED tests/drawing/matplotlib/test_graph.py::GraphTestRunner::test_labels
======================== 1 failed, 509 passed in 22.50s ========================

**Comment by szhorvat** [comment]
I tried this with Fedora Rawhide in Docker.

If I use the `test.sh` script, which install dependencies from PyPI, all tests pass.

If I use Fedora's own matplotlib, I do see this failure. It's not due to igraph, but due to matplotlib, or something matplotlib depends on. The difference is that the label "5" is rendered one pixel lower.

Expected image:

![graph_labels](https://github.com/user-attachments/assets/320f5d01-82d5-42d2-b4a8-4cd44388ceb3)

Actual image:

![graph_labels](https://github.com/user-attachments/assets/cc42aec8-4e7c-43f0-997c-61a9a3bfa42a)

Diff:

![graph_labels-failed-diff](https://github.com/user-attachments/assets/e27bef72-e274-441e-95d2-b77b2e1a038a)

**Comment by limburgher** [comment]
Interesting.

**Comment by QuLogic** [comment]
PyPI wheels are always built with FreeType 2.6. System builds use system dependencies, with latest FreeType that renders a bit different. This would not be limited to Fedora, but also, e.g., conda-forge unless you were using their `testing` label (which bundles older FreeType.)

If you want to check, you can look at `matplotlib.ft2font.__freetype_version__` and set a higher tolerance, or you can leave it to downstreams to patch.

**Comment by ntamas** [comment]
@szhorvat Can we just bump the tolerance then? Since you already set things up in Docker, can you suggest a new threshold that we could use?

**Comment by szhorvat** [comment]
@limburgher Can you please ignore this test for now and get this version into Fedora? The failure clearly doesn't indicate a bug. We'll find a way to deal with the test.

**Comment by limburgher** [comment]
On it!

**Comment by szhorvat** [comment]
3.66 is the lowest tolerance that passes. To do further experimentation, I'd have to re-create the now-deleted Docker environment, which I hope to avoid.

**Comment by ntamas** [comment]
I don't really mind bumping the tolerance to 4.
