### ISSUE TITLE
select() syntax is woeful

### ISSUE THREAD

**Issue by geofurb** [igraph/python-igraph#90]
The select syntax is rather awkward. The statement

    g.vs.select(age_lt=30)

is both kludgy and restrictive. Suggest instead passing in functions and letting select() return a list of vertices for which the function returns true. The revised statement would read:

    g.vs.select(age, lambda x: x < 30)

This is much more readable and flexible. If preserving C operations under-the-hood is desired, it should be straightforward to detect and relay simple inequalities and boolean algebra to native C code. More complicated queries could be evaluated in python at a performance hit or raise an exception.

**Comment by ntamas** [comment]
Note that your revised statement would throw a `NameError` in Python because `age` is an undefined identifier - the revised syntax would probably read as:

```
g.vs.select("age", lambda x: x < 30)
```

You can actually pass a function to `select()` - it will receive all the vertices in the current sequence one by one and then you can return `True` if you want to keep it:

```
g.vs.select(lambda vertex: vertex["age"] < 30)
```

**Comment by geofurb** [comment]
Excellent! That's beautiful, thanks! I would recommend including that example in your tutorial.
