### ISSUE TITLE
damping above 0.85 finishes in finite time only with implementation='power'

### ISSUE THREAD

**Issue by foice** [igraph/python-igraph#92]
Hello, I have no idea of the different prpack and arpack methods, but they seems to be preferred to 'power'. Today I am computing pagerank on a graph with about 1.5M nodes and 20M directed links, and I find result in the 10-100 seconds when damping=0.75 or 0.85, but when I get it to 0.95 neither arpack nor prpack finishes the calculation after few minutes, whereas power finishes  in 10 seconds, giving some meaningful result.

Is this expected? or maybe my networks is somewhat difficult? how can I debug this? 

Thanks,
Roberto

**Comment by ntamas** [comment]
Well, the fact that the power method terminates does not necessarily mean that its result is correct. It may be, or may be not, but the implementation of the power method is somewhat naive so I would even be willing to bet some money on the result not being correct in your particular case. ARPACK and PRPACK are much more battle-tested, so there must be a reason why they take so much time to terminate.

Now, typically, when ARPACK and PRPACK take a long time to terminate, it typically means that the convergence to the PageRank vector is slow. One possible reason - and, actually, the most frequent reason - is that your graph is disconnected and even though the largest connected component converges to the solution quickly, there are some small components with pathological structure that fail to converge or converge very slowly. In other words, even though the PageRank values for most parts of your graph are (nearly) correct after a few iterations, there are a few parts where the results need more iterations to converge. The convergence is slowed down by high damping values, so that's why ARPACK and PRPACK converge fast for 0.75 or 0.85 but not for 0.95.

I would first try to decompose your graph into strongly connected components first, and calculate PageRank values for the individual components. There are clever formulae to combine the PageRank scores of the individual components into a consistent PageRank vector - although I think PRPACK does this already. Anyway, decomposing the graph into strongly connected components and calculating PageRank independently for the different components should help you pinpoint the parts of the graph that converge slowly.

**Comment by foice** [comment]
Thanks a lot for these hints, of course result of power is to be regarded with suspect ... 

I have made tests of more simple nets and I think my issue is a lot more basic, maybe you want to have a look at the results on the net studied on this page [http://www.math.cornell.edu/~mec/Winter2009/RalucaRemus/Lecture3/lecture3.html](http://www.math.cornell.edu/~mec/Winter2009/RalucaRemus/Lecture3/lecture3.html)


I do 

     small_graph.add_vertices(4)
     new_edges=list([[0, 3],[0, 2],[0, 1],[2, 0],[3, 2],[3, 0],[1, 2],[1, 3]])
     small_graph.add_edges(new_edges)
     small_graph.pagerank(damping=0.9999, implementation='power')
     small_graph.pagerank(damping=0.9999)

and the output does match with the results given in the webapge, which can be verified to be correct by simple brute-force taking power of the matrix. On the contrary in Wolfram Mathematica I get the PageRank correctly for damping=1 

     graph = Map[DirectedEdge[#[[1]], #[[2]]] &, {{1, 4}, {1, 3}, {1, 2}, {3, 1}, {4,3}, {4, 1}, {2, 3}, {2, 4}}]
     PageRankCentrality[graph, 0.95]

gives

    0.380907,0.196353,0.28962,0.13312

What am I doing wrong with iGraph?

**Comment by ntamas** [comment]
Most likely your `small_graph` is undirected. It works just fine for me with directed graphs in Python:

```
>>> small_graph = Graph(directed=True)
>>> small_graph.add_vertices(4)
>>> new_edges = [[0, 3],[0, 2],[0, 1],[2, 0],[3, 2],[3, 0],[1, 2],[1, 3]]
>>> small_graph.add_edges(new_edges)
>>> small_graph.pagerank(damping=1)
[0.3870967741935484,
 0.12903225806451613,
 0.29032258064516125,
 0.1935483870967742]
```

The second and the fourth coordinate of the PageRank vector seems to be swapped compared to Mathematica, but it is the same as the one on the webpage.

By the way, trying with `damping=0.999999` and `implementation="power"` shows slightly different results than without `implementation="power"`, which also demonstrates that `implementation="power"` is probably unreliable as it stops too early:

```
>>> small_graph.pagerank(damping=0.999999)
[0.3870966516649068,
 0.1290323381894184,
 0.29032256737771633,
 0.19354844276795852]
>>> small_graph.pagerank(damping=0.999999, implementation="power")
[0.38660289128467795,
 0.12910887527781642,
 0.29048030969906213,
 0.1938079237384434]
```

Using a smaller `eps` value and a larger number of iterations helps, though:

```
small_graph.pagerank(damping=0.999999, implementation="power", niter=100000, eps=1e-7)
[0.3870966211204384,
 0.12903235901624335,
 0.29032256436317816,
 0.19354845550014022]
```

**Comment by foice** [comment]
Thanks for pointing out that I have to specify explicitly that the graph is directed!
