### ISSUE TITLE
cannot read a graph from an io object

### ISSUE THREAD

**Issue by yawara** [igraph/python-igraph#94]
I want to read a graph from an io object as follows:

```python
import igraph
import io

G = igraph.Graph.Read_Edgelist(io.BytesIO(b'0 1'))
```

but it raised the following error.

```
io.UnsupportedOperation: fileno
```

**Comment by ntamas** [comment]
This is normal; `Graph.Read_Edgelist()` just calls out to `igraph_read_graph_edgelist()` in C (since igraph is implemented in C), which takes a `FILE*` argument. If you don't supply a "normal" file or the name of a file to `Graph.Read_Edgelist()`, it will attempt to create a `FILE*` pointer for the C layer by calling `fileno()` on the input argument in Python to obtain a file descriptor, then calling `fdopen()` on the file descriptor in the C layer to convert it into a `FILE*`.

The workaround is to write the `BytesIO` object into a temporary file and then use that temporary file as an argument to `Read_Edgelist()`.
